# Análisis y visualización de datos con Python
# 6. Limpieza de datos

    - a) Estrategia de limpieza
    - b) Valores faltantes y duplicados
    - c) Eliminación
    - d) Limpieza de texto
    - e) Limpieza de categóricos
    - f) Limpieza de números
    - g) Limpieza de fechas
    - h) Ordenar y guardar datos
    - i) Resumen

---

La limpieza de datos es el proceso de identificar, corregir o eliminar datos incorrectos, incompletos, irrelevantes o duplicados en un conjunto de datos. La limpieza de datos es importante para garantizar la precisión y la calidad de los datos y evitar errores en el análisis posterior. 

Empezaremos cargando los datos.

In [1]:
from numpy import nan
import pandas as pd

filename = 'data_raw/CNB_DOB_BPGS_Respuesta_Solicitud 332163723000249.xlsx'
df = pd.read_excel(filename, sheet_name="HBO", index_col='ID', dtype='str')
df

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Procedencia_estandar,...,Diagnostico_estandar,Diagnostico_extendido,Sexo,Edad_transcrito,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_00001,S-D,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,1968-01-03 00:00:00,37,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00002,S-D,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,1968-01-05 00:00:00,58,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00003,S-D,arzate paredes juan,arzate,paredes,juan,1968-01-07,1968-01-07 00:00:00,83,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00004,S-D,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,1968-01-07 00:00:00,86,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
BO_1968_00005,S-D,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,1968-01-07 00:00:00,88,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Cadáver,semefo_df_bo_1968,2,1,NaN,conocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_07489,S-D,placenta,s-d,s-d,s-d,1982-06-05,1982-06-05 00:00:00,3079,15a,15A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07490,S-D,5 dedos del pie derecho de desconocido,s-d,s-d,s-d,1982-06-05,1982-06-05 00:00:00,3060,32a,32A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07491,S-D,dedo de desconocido,s-d,s-d,s-d,1982-11-19,1982-11-19 00:00:00,6389,32a,32A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07492,S-D,4 dedos de desconocido,s-d,s-d,s-d,1982-11-28,1982-11-28 00:00:00,6528,27a,27A,...,S-D,sin datos,S-D,S-D,Miembros,semefo_df_bo_1982,251,156,NaN,desconocido
BO_1982_07493,S-D,osamenta de desconocido,s-d,s-d,s-d,1982-10-11,1982-10-11 00:00:00,5629,9a,9A,...,S-D,sin datos,S-D,S-D,Cadáver,semefo_df_bo_1982,251,156,no se recibio necropsia. es una osamenta.,desconocido

Cómo vimos anteriormente hay varios tipos de datos como: texto, numérico, fecha, etc.
De manera automática, Pandas infiere el tipo de datos al leer el archivo, de una manera muy similar a como Excel interpreta si un dato es texto, número o fecha.

Los tipos de datos de pandas son:
* `object`: texto o mezcla de varios tipos de datos, este es el tipo de dato por defecto
* `category`: información categórica, similar a Factors en R
* `int64`: números enteros
* `float64`: números con punto decimal
* `bool`: valores verdadero o falso
* `datetime64`: fechas
* `timedelta[ns]`: diferencias de tiempo

Podemos ver los tipos de datos inferidos usando la opción `.dtypes`.

Dependiendo del tipo de dato se pueden hacer diferentes operaciones y hay tipos de limpieza específica.

In [2]:
df.dtypes

Numero_progresivo_transcrito    object
Nombre_completo_transcrito      object
Primer_apellido                 object
Segundo_apellido                object
Nombres_propios                 object
Fecha_transcrito                object
Fecha_estandar                  object
Expediente_SEMEFO_transcrito    object
Procedencia_transcrito          object
Procedencia_estandar            object
Procedencia_direccion           object
Procedencia_alcaldia            object
Numero_acta_transcrito          object
Procedencia_acta                object
Diagnostico_transcrito          object
Diagnostico_estandar            object
Diagnostico_extendido           object
Sexo                            object
Edad_transcrito                 object
Tipo_restos                     object
Bitacora_ingresos               object
Pagina_PDF                      object
Foja_transcrito                 object
Observaciones                   object
Conocido_desconocido            object
dtype: object

## 6.a Estrategia de limpieza

En ciencia de datos, una variable limpia se refiere a una variable libre de errores, inconsistencias o artefactos no deseados que podrían comprometer el análisis. Esto significa que los datos son:

* Consistentes: siguen un formato uniforme
* Completos: los valores faltantes son rellenados, eliminados, imputados o ignorados.
* Precisos: libres de valores incorrectos, desactualizados o mal ingresados
* Válidos: cumplen con las restricciones esperadas, por ejemplo, tipo y rango
* Únicos: los duplicados se manejan según sea necesario.

En el caso de todas las variables es necesario revisar y tratar:
* Tipo de datos
* Valores faltantes
* Duplicados

Dependiendo de la variable es recomendable:
* Validar rangos y restricciones
* Detectar valores atípicos (outliers)
* Estandarizar y normalizar datos
* Validar datos categóricos
* Comprobar coherencia lógica

Para esto es recomendable revisar el conjunto de datos y el perfil de datos para generar una tabla de limpieza. Esta tabla incluye la variable, el tipo esperado, los pasos necesarios de limpieza y pasos de validación particulares a la variable.

Variable | Tipo | Limpieza | Validación
---------|------|----------|------------
ID | Alfanumérico |  | Patron: BO_19aa_ddddd
Numero_progresivo_transcrito | Texto | quitar S-D | original
Nombre_completo_transcrito | Texto |  | original
Primer_apellido | Texto | quitar acentos, espacios extra, pasar minúsculas | revisar faltantes
Segundo_apellido | Texto | quitar acentos, espacios extra, pasar minúsculas | revisar faltantes
Nombres_propios | Texto | quitar acentos, espacios extra, pasar minúsculas | revisar faltantes
Fecha_transcrito | Texto |  | original
Fecha_estandar | Fecha | regenerar to_datetime | rango
Expediente_SEMEFO_transcrito | Texto |  | original
Procedencia_transcrito | Texto | quitar acentos, espacios extra, pasar minúsculas | original
Procedencia_estandar | Catálogo | regenerar y estandarizar cat_proc_sustitucion | verificar en catálogo
Numero_acta_transcrito | Texto |  | original
Procedencia_acta | Alfanumérico | quitar | 
Diagnostico_transcrito | Texto |  | original
Diagnostico_estandar | Catálogo | regenerar estandarizar cat_diag_sustitucion | verificar en catálogo
Sexo | Catálogo |  | verificar en catálogo
Edad_transcrito | Texto |  | original
Edad_estandar | Numérico | regenerar to_numeric | rango
Tipo_restos | Catálogo | quitar baja frecuencia | verificar en catálogo
Bitacora_ingresos | Catálogo |  | verificar en catálogo
Pagina_PDF | Numérico | quitar | 
Foja_transcrito | Texto | quitar | 
Observaciones | Texto | quitar | 
Conocido_desconocido | Catálogo | verificar S-D | verificar en catálogo

Una consideración importante es si se modificara la columna original o se generará una columna nueva con los datos limpios. Qué opción se escoge depende de varios factores, cómo el tamaño de la tabla o si nos interesa conservar la información original. En este tutorial crearemos columnas nuevas para poder contrastar los cambios y al final quitaremos las que no nos interesen.

### Ingeniería de atributos

Cuando se generan nuevas variables de datos a partir de las existentes se le llama "creación de características" o "ingeniería de características" (en inglés, feature engineering). Es una técnica comúnmente utilizada en el análisis de datos para mejorar la precisión de los modelos de machine learning o para encontrar patrones y tendencias en los datos. La idea es generar nuevas variables a partir de las ya existentes que puedan ser más relevantes o informativas para el problema en cuestión. Este proceso se puede hacer también durante el análisis de datos, dependiendo de lo que se necesite. 

Por ejemplo, se tiene la variable `Edad_transcrito`, la cual limpiaremos y guardaremos en la variable `Edad_estandar`. A partir de esta podemos obtener los grupos de edad y guardarlos en una nueva variable llamada `Edad_grupos`.

Al hacer la tabla de limpieza, es útil incluir las variables nuevas.

Variable | Tipo | Limpieza | Validación
---------|------|----------|------------
Fecha_año | Numérico |  | rango
Fecha_mes | Numérico |  | rango
Fecha_diasemana | Catálogo |  | verificar en catálogo
Procedencia_extendido | Catálogo | estandarizar cat_proc_sustitucion | verificar en catálogo
Procedencia_alcadía | Catálogo | estandarizar cat_proc_sustitucion | verificar en catálogo
Diagnostico_extendido | Catálogo | estandarizar cat_diag_sustitucion | verificar en catalogo
Edad_grupo | Catálogo | estandarizar con INEGI | verificar en catálogo

## 6.b Valores faltantes y duplicados

Un valor faltante es un valor que falta o está incompleto en un conjunto de datos. A menudo, los valores faltantes se deben a errores de entrada de datos, fallas en la recolección de datos o problemas técnicos. Los valores faltantes pueden aparecer como espacios en blanco, ceros, letras u otros caracteres. La presencia de valores faltantes en un conjunto de datos puede afectar la precisión y la calidad del análisis de los datos, por lo que es importante identificarlos y manejarlos adecuadamente durante la limpieza y el preprocesamiento de los datos.

Por ejemplo, en el caso de los nombres podemos ver varios casos de datos faltantes.  Cada uno de estos representa diferentes tipos de falta de información y amerita un tratamiento diferente.
* "s-d": de acuerdo a la información proporcionada con el conjunto de datos, esto significa que el espacio que corresponde al nombre se encuentra vacío en las Bitácoras originales, y por lo tanto se transcribió como s-d para reflejar la falta de información de origen
* "desconocido" y "desconocida": en este caso, el SEMEFO desconoce la identidad del ingreso
* "Nombre de particular que podría encontrarse con vida. Se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP.": en este caso el nombre se oculta por protección de datos personales
* `nan` esto sucede cuando la celda está vacía, en este caso no hay celdas vacías


La falta de información es, en sí misma, información sobre el conjunto de datos.

In [3]:
df['Nombre_completo_transcrito'].value_counts().head(10).to_frame()

                                                    count
Nombre_completo_transcrito
desconocido                                         12828
feto                                                 2610
Nombre de particular que podría encontrarse con...   2158
desconocida                                          1294
r. nacido                                             224
recien nacido                                         105
r. nacida                                              96
recien nacida                                          61
r nacido                                               34
osamenta                                               30

Podemos ver la cantidad de datos faltantes con el profile o la función `.isna()`

In [4]:
df.isna().sum()

Numero_progresivo_transcrito        0
Nombre_completo_transcrito          0
Primer_apellido                  1878
Segundo_apellido                  281
Nombres_propios                  2095
Fecha_transcrito                    0
Fecha_estandar                    266
Expediente_SEMEFO_transcrito        0
Procedencia_transcrito              0
Procedencia_estandar              408
Procedencia_direccion             437
Procedencia_alcaldia            31946
Numero_acta_transcrito              0
Procedencia_acta                25635
Diagnostico_transcrito              0
Diagnostico_estandar             8267
Diagnostico_extendido            8267
Sexo                                0
Edad_transcrito                     0
Tipo_restos                         0
Bitacora_ingresos                   0
Pagina_PDF                          0
Foja_transcrito                     0
Observaciones                   82723
Conocido_desconocido                0
dtype: int64

Para determinar si debemos de quitar filas por la cantidad de datos faltantes hay que analizar la cantidad de faltantes y su distribución.

**Nota** Explicación del comando
```
df.isna()         <-- determinar si las celdas son na
  .sum(axis=1)    <-- sumar los faltantes por fila
  .value_counts() <-- contar cuantas veces aparece cada número
  .sort_index()   <-- ordenar por el indice, que en este caso es el número de faltantes
```

In [5]:
df.isna().sum(axis=1).value_counts().sort_index()

0     9821
1    46700
2     7775
3    30780
4     1362
5      281
6      117
7        7
9        1
Name: count, dtype: int64

Cómo podemos ver, hay 406 filas donde faltan 5 o más valores. Revisemos estas filas. La mayor parte de los datos faltantes corresponden a casos donde se borraron los nombres para proteger datos personales, aunque también hay datos faltantes en las observaciones y el diagnóstico.

In [6]:
df[  df.isna().sum(axis=1)>=5  ]

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Procedencia_estandar,...,Diagnostico_estandar,Diagnostico_extendido,Sexo,Edad_transcrito,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_00842,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1968-02-08,1968-02-08 00:00:00,543,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1968,30,19 reverso,NaN,conocido
BO_1968_03002,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1968-04-22,1968-04-22 00:00:00,1170,H.E.V.,NaN,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1968,101,73 reverso,NaN,conocido
BO_1968_03007,S-D,Nombre de particular que podría encontrarse co...,NaN,s-d,NaN,1968-04-06,1968-04-06 00:00:00,1386,S-D,S-D,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1968,102,74,NaN,conocido
BO_1968_03145,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1968-07-18,1968-07-18 00:00:00,2561,Cruz Roja,CR,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1968,106,76,NaN,conocido
BO_1969_01269,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1969-01-03,1969-01-03 00:00:00,42,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Feto,semefo_df_bo_1969,44,30,NaN,conocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_07407,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-07-02,1982-07-02 00:00:00,3109,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,247,153 reverso,NaN,conocido
BO_1982_07408,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-07-08,1982-07-08 00:00:00,3809,32a,32A,...,S-D,sin datos,Femenino,S-D,Miembros,semefo_df_bo_1982,247,153 reverso,NaN,conocido
BO_1982_07409,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-07-10,1982-07-10 00:00:00,3831,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,247,153 reverso,NaN,conocido
BO_1982_07450,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-11-06,1982-11-06 00:00:00,6095,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,249,154 reverso,NaN,conocido
BO_1982_07474,S-D,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,1982-12-15,1982-12-15 00:00:00,6897,32a,32A,...,S-D,sin datos,Masculino,S-D,Miembros,semefo_df_bo_1982,249,154 reverso,NaN,conocido

Existen diversas estrategias para abordar tratar los datos faltantes, dependiendo del tipo de datos, cantidad de faltantes, distribución de la variable y el contexto del análisis. Las dos principales estrategias son la **eliminación** de las filas y/o columnas con datos faltantes y la **imputación** de valores faltantes.

Algunos ejemplos de imputación
* Reemplazan los valores nulos con un valor arbitrario (0, -1, "desconocido", etc.)
* Crear una nueva categoría indicando que el valor está ausente
* Imputación con estadísticos media (sin sesgo), mediana (con sesgo), moda(categórico)
* Imputación basada en modelos estimando el valor
* Interpolación temporal


Es importante verificar si hay datos duplicados, ya que estos pueden ser señal de errores durante la generación de datos o causar errores en el análisis.
Podemos hacer esto con `.duplicated(keep=False)`. 
Es importante notar que aunque el índice sea único, sí se detectan líneas duplicadas.

En este caso no encontramos varios tipos de duplicados. En algunos casos parecen ser personas que aparecen varias veces y que tienen todos los datos, incluido el nombre completo, idénticos. Por otro lado, hay casos, como los desconocidos, donde hay una gran falta de información de origen, por lo que el hecho de que las filas sean duplicadas puede ser un indicador de la falta de información, la cual impide distinguir los casos.

In [7]:
df[ df.duplicated(keep=False) ]

,Numero_progresivo_transcrito,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Expediente_SEMEFO_transcrito,Procedencia_transcrito,Procedencia_estandar,...,Diagnostico_estandar,Diagnostico_extendido,Sexo,Edad_transcrito,Tipo_restos,Bitacora_ingresos,Pagina_PDF,Foja_transcrito,Observaciones,Conocido_desconocido
ID,,,,,,,,,,,,,,,,,,,,,
BO_1968_01734,S-D,gomez caballero pedro,gomez,caballero,pedro,1968-07-11,1968-07-11 00:00:00,2480,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,60,39,NaN,conocido
BO_1968_01736,S-D,gomez caballero pedro,gomez,caballero,pedro,1968-07-11,1968-07-11 00:00:00,2480,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,60,39,NaN,conocido
BO_1968_02175,S-D,desconocido,s-d,s-d,s-d,1968-07-11,1968-07-11 00:00:00,2479,11a Del.,11A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,74,49,NaN,desconocido
BO_1968_02177,S-D,desconocido,s-d,s-d,s-d,1968-07-11,1968-07-11 00:00:00,2479,11a Del.,11A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,74,49,NaN,desconocido
BO_1968_02595,S-D,desconocido,s-d,s-d,s-d,1968-12-03,1968-12-03 00:00:00,4393,1a Del.,1A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1968,88,56 reverso,NaN,desconocido
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
BO_1982_05377,S-D,sanchez carranza isaias,sanchez,carranza,isaias,1982-10-12,1982-10-12 00:00:00,5657,HB,HTB,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,180,108 reverso,NaN,conocido
BO_1982_05378,S-D,suarez hernandez jesus,suarez,hernandez,jesus,1982-10-11,1982-10-11 00:00:00,5644,15a,15A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,180,108 reverso,NaN,conocido
BO_1982_05379,S-D,salazar patino javier,salazar,patino,javier,1982-10-09,1982-10-09 00:00:00,5589,1a,1A,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,180,108 reverso,NaN,conocido
BO_1982_07188,S-D,desconocido,s-d,s-d,s-d,S-D,NaN,S-D,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,239,144,NaN,desconocido
BO_1982_07206,S-D,desconocido,s-d,s-d,s-d,S-D,NaN,S-D,S-D,S-D,...,S-D,sin datos,Masculino,S-D,Cadáver,semefo_df_bo_1982,239,144,NaN,desconocido

## 6.c Eliminación

Es posible que no todos los datos contenidos en el conjunto de datos sean utilizables o de interés. Eliminarlos facilita el análisis y eficientiza el uso de memoria.

Algunas razones para eliminar filas o columnas son:
* Baja variabilidad, por ejemplo una columna donde todos los valores son iguales
* Información repetida, por ejemplo filas idénticas
* Gran cantidad de datos faltantes
* Información no relevante para el análisis.

En este tutorial usaremos una estrategia donde primero revisaremos los datos, marcaremos las columnas a quitar, y las quitaremos todas al final. Sin embargo, se indican comandos útiles para quitar filas.


### Datos duplicados

En este caso, dado que no podemos distinguir la razón de la duplicación de filas y que nos interesa analizar un conjunto de datos histórico, no quitaremos filas. Sin embargo, es posible quitar filas y columnas duplicadas con el comando: `.drop_duplicates()`.


### Gran cantidad de faltantes

Una razón para quitar variables o filas es por qué hay una gran cantidad de faltantes. Una métrica general es quitar las variables en las que falta más del 10% de los datos, aunque es recomendable revisar cuáles son antes de hacer esta operación.

En este caso, marcaremos que las columnas a quitar son `Procedencia_alcaldia`, `Procedencia_acta` y `Observaciones` y las quitaremos más adelante.

In [8]:
df.isna().sum() / df.shape[0] * 100

Numero_progresivo_transcrito     0.000000
Nombre_completo_transcrito       0.000000
Primer_apellido                  1.939201
Segundo_apellido                 0.290157
Nombres_propios                  2.163273
Fecha_transcrito                 0.000000
Fecha_estandar                   0.274669
Expediente_SEMEFO_transcrito     0.000000
Procedencia_transcrito           0.000000
Procedencia_estandar             0.421296
Procedencia_direccion            0.451241
Procedencia_alcaldia            32.987072
Numero_acta_transcrito           0.000000
Procedencia_acta                26.470406
Diagnostico_transcrito           0.000000
Diagnostico_estandar             8.536409
Diagnostico_extendido            8.536409
Sexo                             0.000000
Edad_transcrito                  0.000000
Tipo_restos                      0.000000
Bitacora_ingresos                0.000000
Pagina_PDF                       0.000000
Foja_transcrito                  0.000000
Observaciones                   85.418818
Conocido_desconocido             0.000000
dtype: float64

Otra situación es cuando la columna o fila solo tiene algunos faltantes, en este caso es necesario tomar decisiones dependiendo de la situación. Por ejemplo, en el caso de la columna 'Numero_progresivo_transcrito' el 72% de los datos son 'S-D', es decir, no hay datos. Dado que nuestro estudio se centra en describir la población y no los procesos administrativos, y la gran cantidad de variables, podemos ignorarla.

In [9]:
df['Numero_progresivo_transcrito'].value_counts(normalize=True).head(5)

Numero_progresivo_transcrito
S-D    0.719435
41     0.001136
38     0.001136
37     0.001126
40     0.001126
Name: proportion, dtype: float64

Por otro lado, en el caso de la columna 'Edad_transcrito' el 58% de los datos son 'S-D', es decir, no hay datos. Sin embargo, esta variable es de gran interés, por lo que la procesaremos para obtener la mayor cantidad de edades posibles y usarla en el análisis.

In [10]:
df['Edad_transcrito'].value_counts(normalize=True).head(5)

Edad_transcrito
S-D    0.585075
40     0.017843
30     0.017668
35     0.017203
25     0.016707
Name: proportion, dtype: float64

El comando `dropna()` sirve para quitar filas (`axis=0`) o columnas (`axis=1`). Existen varias opciones:

* `how='any'` quita las filas o columnas donde hay al menos un `nan`, este parámetro es el default
* `how='all'` quita las filas o columnas donde todos son `nan`
* `thresh=numero` quita las filas o columnas con más de cierto número de `nan`s, esto es útil para detectar automáticamente columnas donde faltan muchos datos

El siguiente comando quita automáticamente las columnas con más del 10% de faltantes.

```
df = df.dropna(thresh=round( df.shape[0]*0.10), axis=1)
```

### Información no relevante

Los conjuntos de datos muchas veces contienen información que no es relevante para el análisis. Para determinar si la información es relevante o no es necesario tener clara la pregunta de investigación y los objetivos del análisis.

Por ejemplo, en este curso nos interesa analizar las características demográficas de los ingresos al SEMEFO. Por lo tanto, columnas que describen variables demográficas cómo 'Edad' y 'Sexo' son de gran interés. Por otro lado, columnas cómo 'Numero_progresivo_transcrito' o 'Pagina_PDF', las cuales describen la localización en la bitácora y el proceso administrativo, no son de interés.

Además, en este tutorial regeneraremos las columnas de datos estandarizadas cómo 'Procedencia_estandar' y 'Diagnostico_estandar', por lo cual eliminaremos estas columnas.

### Drop: eliminar variables

Para esto usaremos el comando `.drop()`. Recuerda que el parámetro `axis=0` se refiere a filas y `axis=1` a columnas.

Para guardar estas modificaciones debemos de actualizar el dataframe. Recuerda verificar antes de eliminar información.

In [11]:
df.columns

Index(['Numero_progresivo_transcrito', 'Nombre_completo_transcrito',
       'Primer_apellido', 'Segundo_apellido', 'Nombres_propios',
       'Fecha_transcrito', 'Fecha_estandar', 'Expediente_SEMEFO_transcrito',
       'Procedencia_transcrito', 'Procedencia_estandar',
       'Procedencia_direccion', 'Procedencia_alcaldia',
       'Numero_acta_transcrito', 'Procedencia_acta', 'Diagnostico_transcrito',
       'Diagnostico_estandar', 'Diagnostico_extendido', 'Sexo',
       'Edad_transcrito', 'Tipo_restos', 'Bitacora_ingresos', 'Pagina_PDF',
       'Foja_transcrito', 'Observaciones', 'Conocido_desconocido'],
      dtype='object')

In [12]:
col_drop = [
            'Numero_progresivo_transcrito', 'Fecha_estandar', 'Expediente_SEMEFO_transcrito', 
            'Procedencia_estandar', 'Procedencia_direccion', 'Procedencia_alcaldia','Procedencia_acta', 
            'Numero_acta_transcrito', 'Diagnostico_estandar', 'Diagnostico_extendido', 
            'Bitacora_ingresos', 'Pagina_PDF', 'Foja_transcrito', 'Observaciones', 
           ]
df = df.drop( col_drop, axis=1)
df.head()

,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Procedencia_transcrito,Diagnostico_transcrito,Sexo,Edad_transcrito,Tipo_restos,Conocido_desconocido
ID,,,,,,,,,,,
BO_1968_00001,acosta ortega teresa,acosta,ortega,teresa,1968-01-03,S-D,S-D,Femenino,S-D,Cadáver,conocido
BO_1968_00002,avila de cuestas catalina,avila,de cuestas,catalina,1968-01-05,S-D,S-D,Femenino,S-D,Cadáver,conocido
BO_1968_00003,arzate paredes juan,arzate,paredes,juan,1968-01-07,S-D,S-D,Masculino,S-D,Cadáver,conocido
BO_1968_00004,alvarez martinez isaac,alvarez,martinez,isaac,1968-01-07,S-D,S-D,Masculino,S-D,Cadáver,conocido
BO_1968_00005,arellano viuda de campos ma.,arellano,viuda de campos,ma.,1968-01-07,S-D,S-D,Femenino,S-D,Cadáver,conocido

## 6.d Limpieza de texto

Durante este proceso de limpieza respetaremos las columnas transcritas directamente del HBO, creando columnas modificadas.

Las columnas transcritas de origen no se van a modificar, pero es importante verificar el formato. Para eso iteraremos sobre las columnas de interés con un `for`. Dentro de este, columna por columna, aplicaremos `apply`, el cual aplicara a cada celda la función `str`, asegurándose de que todos los valores sean _strings_. 

Nota: desde Excel se forzó el formato de la columna 'Fecha_transcrito' a ser texto.

In [13]:
cols = ['Nombre_completo_transcrito', 'Fecha_transcrito', 'Procedencia_transcrito',
        'Diagnostico_transcrito', 'Edad_transcrito']
for col in cols:
    df[col] = df[col].apply(str)

Revisemos que no hayamos convertido `nan`s a texto.

In [14]:
(df[cols]=='nan').sum()

Nombre_completo_transcrito    0
Fecha_transcrito              0
Procedencia_transcrito        0
Diagnostico_transcrito        0
Edad_transcrito               0
dtype: int64

En este conjunto de datos, las columnas de texto a modificar son:
* 'Primer_apellido'
* 'Segundo_apellido'
* 'Nombres_propios'

Primero revisemos los valores de las columnas. El profile inicial nos da una buena idea de los valores de las columnas, pero es bueno revisar los valores más comunes de las columnas relacionadas

In [15]:
col_str = ['Primer_apellido', 'Segundo_apellido', 'Nombres_propios']
df[['Nombre_completo_transcrito']+col_str].value_counts(dropna=False).head(25).reset_index()

,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,count
0,desconocido,s-d,s-d,s-d,12827
1,feto,s-d,s-d,s-d,2610
2,Nombre de particular que podría encontrarse co...,NaN,s-d,NaN,1591
3,desconocida,s-d,s-d,s-d,1293
4,Nombre de particular que podría encontrarse co...,s-d,s-d,NaN,272
5,Nombre de particular que podría encontrarse co...,NaN,NaN,NaN,229
6,r. nacido,s-d,s-d,s-d,224
7,recien nacido,s-d,s-d,s-d,105
8,r. nacida,s-d,s-d,s-d,96
9,recien nacida,s-d,s-d,s-d,61
10,Nombre de particular que podría encontrarse co...,NaN,NaN,s-d,49
11,r nacido,s-d,s-d,s-d,34
12,osamenta,s-d,s-d,s-d,30
13,restos humanos,s-d,s-d,s-d,26
14,s-d,s-d,s-d,s-d,24
15,r nacida,s-d,s-d,s-d,11
16,placenta,s-d,s-d,s-d,11
17,restos oseos,s-d,s-d,s-d,8
18,m.i. de:,s-d,s-d,s-d,8
19,miembro inferior,s-d,s-d,s-d,7
20,Nombre de particular que podría encontrarse co...,NaN,s-d,s-d,7
21,hernandez hernandez jesus,hernandez,hernandez,jesus,7
22,lopez lopez mario,lopez,lopez,mario,6
23,m. inf.,s-d,s-d,s-d,6
24,garcia garcia juan,garcia,garcia,juan,6

### Remplazar valores

En este caso podemos notar que los datos están extremadamente limpios. Haremos dos modificaciones.

En el caso de 'Primer_apellido', 'Segundo_apellido' y 'Nombres_propios' sustituiremos 's-d' por `np.nan`

En el caso de 'Nombre_completo_transcrito' sustituiremos la leyenda 'Nombre de particular que podría encontrarse con vida. Se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP' por 'nombre confidencial' y 's-d' por 'S-D'.

Para sustituir los valores usaremos la función `.replace()`. Es muy importante copiar exactamente el texto  a sustituir.

In [16]:
# Diccionario de sustitución
replace_str = {'s-d':'S-D',
               'Nombre de particular que podría encontrarse con vida. Se clasifica como confidencial con fundamento en el artículo 116 de la LGTAIP.':'nombre confidencial'
              }
# Aplicamos función a columna de interes
df['Nombre_completo_transcrito'] = df['Nombre_completo_transcrito'].replace(replace_str)
# Revisamos resultado
df['Nombre_completo_transcrito'].value_counts(25).head()

Nombre_completo_transcrito
desconocido            0.132460
feto                   0.026951
nombre confidencial    0.022283
desconocida            0.013362
r. nacido              0.002313
Name: proportion, dtype: float64

In [17]:
# Revisar que no queden los valores que sustituimos
df[ df['Nombre_completo_transcrito'].isin(replace_str.keys()) ]

Empty DataFrame
Columns: [Nombre_completo_transcrito, Primer_apellido, Segundo_apellido, Nombres_propios, Fecha_transcrito, Procedencia_transcrito, Diagnostico_transcrito, Sexo, Edad_transcrito, Tipo_restos, Conocido_desconocido]
Index: []

Podemos aplicar `.replace()` a un subconjunto de columnas (`col_str`), en ese caso es necesario aplicar y guardar dentro del mismo subconjunto.

Nota: se importó `nan` al inicio del notebook con `from numpy import nan`.

In [18]:
col_str = ['Primer_apellido', 'Segundo_apellido', 'Nombres_propios']
df[col_str] = df[col_str].replace('s-d',nan)
df[['Nombre_completo_transcrito']+col_str].value_counts(dropna=False).head(25)

Nombre_completo_transcrito   Primer_apellido  Segundo_apellido  Nombres_propios
desconocido                  NaN              NaN               NaN                12827
feto                         NaN              NaN               NaN                 2610
nombre confidencial          NaN              NaN               NaN                 2151
desconocida                  NaN              NaN               NaN                 1293
r. nacido                    NaN              NaN               NaN                  224
recien nacido                NaN              NaN               NaN                  105
r. nacida                    NaN              NaN               NaN                   96
recien nacida                NaN              NaN               NaN                   61
r nacido                     NaN              NaN               NaN                   34
osamenta                     NaN              NaN               NaN                   30
restos humanos               NaN              NaN               NaN                   26
S-D                          NaN              NaN               NaN                   24
r nacida                     NaN              NaN               NaN                   11
placenta                     NaN              NaN               NaN                   11
restos oseos                 NaN              NaN               NaN                    8
m.i. de:                     NaN              NaN               NaN                    8
hernandez hernandez jesus    hernandez        hernandez         jesus                  7
miembro inferior             NaN              NaN               NaN                    7
m. inf.                      NaN              NaN               NaN                    6
fetos                        NaN              NaN               NaN                    6
lopez lopez mario            lopez            lopez             mario                  6
hernandez hernandez antonio  hernandez        hernandez         antonio                6
garcia garcia juan           garcia           garcia            juan                   6
lopez hernandez juan         lopez            hernandez         juan                   5
hernandez gonzalez jose      hernandez        gonzalez          jose                   5
Name: count, dtype: int64

### Capitalización

En este caso, los datos están bastante limpios, para mostrar las siguientes operaciones usaremos de ejemplo los **datos de adopciones del DIF**. En particular, nos centraremos en los nombres de columna.

In [19]:
# Leer el archivo
s_adop = pd.read_excel('data_raw/Adopciones_JULIO-DICIEMBRE_2024.xlsx')
# Obtener solo los nombres de columna y transformar a pd.Series
s_adop = pd.Series( s_adop.columns )
s_adop

0                        Reporte Semestral de Adopción
1                                               Periodo
2                     Institución Encargada del Trámite
3                                 Solicitudes Recibidas
4                               Solicitudes  en Trámite
5     Solicitudes de adopción con resolución sobre l...
6     Solicitudes de adopción con resolución sobre l...
7                                 Adopciones concluidas
8                                              Femenino
9                                            Masculino
10                         Niñas de 0 - 4 años 11 meses
11                         Niñas de \n5-8 años 11 meses
12        Niñas y adolescentes mujeres de  \n9 -18 años
13                                       Total de Niñas
14                         Niños de 0 - 4 años 11 meses
15                          Niños de  5-8 años 11 meses
16          Niños y adolescentes hombre de 9 - 13 años
17        Niños y adolescentes hombres de 14 - 18 años
18                                       Total de Niños
19                                    Estado de Origen
20                                   Estado de Receptor
dtype: object

Si revisamos cuidadosamente los datos veremos varios detalles:
* Textos empiezan o terminan con espacios
* Espacios dobles, saltos de línea `\n` dentro del texto, etc.
* Uso irregular de mayúsculas
* Irregularidad de formato '0 - 4' y '5-8'
* Acentos y caracteres especiales en texto

In [20]:
s_adop.to_list()

['Reporte Semestral de Adopción ',
 'Periodo',
 'Institución Encargada del Trámite',
 'Solicitudes Recibidas',
 'Solicitudes  en Trámite',
 'Solicitudes de adopción con resolución sobre la no emisión del Certificado de Idoneidad',
 'Solicitudes de adopción con resolución sobre la improcedencia',
 'Adopciones concluidas',
 'Femenino',
 'Masculino ',
 'Niñas de 0 - 4 años 11 meses',
 'Niñas de \n5-8 años 11 meses',
 'Niñas y adolescentes mujeres de  \n9 -18 años',
 'Total de Niñas',
 'Niños de 0 - 4 años 11 meses',
 'Niños de  5-8 años 11 meses',
 'Niños y adolescentes hombre de 9 - 13 años ',
 'Niños y adolescentes hombres de 14 - 18 años ',
 'Total de Niños',
 'Estado de Origen ',
 'Estado de Receptor']

Es posible cambiar la capitalización de los textos:
* `.upper()` todas mayúsculas
* `.lower()` todas minúsculas
* `.title()` primera letra de todas las palabras en mayúscula
* `.capitalize()` primera letra de la oración en mayúscula

Estas se pueden aplicar tanto a textos en formato string (`str`) cómo a `pd.Series`

In [21]:
'SwApCaSe'.lower()

'swapcase'

In [22]:
s_adop.str.lower()

0                        reporte semestral de adopción
1                                               periodo
2                     institución encargada del trámite
3                                 solicitudes recibidas
4                               solicitudes  en trámite
5     solicitudes de adopción con resolución sobre l...
6     solicitudes de adopción con resolución sobre l...
7                                 adopciones concluidas
8                                              femenino
9                                            masculino
10                         niñas de 0 - 4 años 11 meses
11                         niñas de \n5-8 años 11 meses
12        niñas y adolescentes mujeres de  \n9 -18 años
13                                       total de niñas
14                         niños de 0 - 4 años 11 meses
15                          niños de  5-8 años 11 meses
16          niños y adolescentes hombre de 9 - 13 años
17        niños y adolescentes hombres de 14 - 18 años
18                                       total de niños
19                                    estado de origen
20                                   estado de receptor
dtype: object

### Acentos, puntuación y caracteres especiales

Se pueden clasificar los caracteres de varias maneras:
* Letras: A-Z, a-z
* Dígitos: 0-9
* Letras con acentos y diacríticos: á, é, í, ó, ú, ü, ñ, ç.
* Puntuación básica: ! " , . ?  
* Puntuación extendida: ¿, ¡, «, », —, •, ….
* Símbolos matemáticos: ∞, ±, ≠, ≤, ≥, ∑, √.
* Caracteres especiales de control: salto de línea '\n', tabulación '\t'
* Emojis y Pictogramas: 😀 ❤️
* Caracteres de idiomas no latinos: Ω Я 漢

RegExp (Expresiones Regulares) es un conjunto de patrones utilizados para buscar, extraer y manipular texto de manera eficiente. Se usa en muchos lenguajes de programación para validar formatos, reemplazar cadenas y filtrar datos. Las expresiones regulares permiten identificar y procesar caracteres especiales en texto. 
Las expresiones regulares son muy ricas, pero puede ser complicado usarlas, una alternativa es utilizar una IA generativa para que ayude a construir la expresión.

In [23]:
import re
texto = "Hola, ¿cómo estás?"
res = re.sub(r"[^\w\s]", "", texto)  # Elimina caracteres especiales
print(res)

Hola cómo estás

En español un problema común es procesar textos con acentos. Por ejemplo, es relativamente común tener nombres capturados a mano con y sin acentos, lo cual puede complicar el buscar patrones.

Para quitar los acentos se usa la función `unidecode()`, la cual es parte de la biblioteca `unidecode`. Es importante tener en cuenta que transforma las 'ñ' a 'n'.

In [24]:
from unidecode import unidecode
unidecode('á, é, í, ó, ú, ü, ñ, ç')

'a, e, i, o, u, u, n, c'

Podemos aplicar esta función a toda la columna, usando `.apply(), ya que no es una función default de pandas. Estas modificaciones son temporales. Para guardar los resultados es necesario guardar la columna o serie generada. Esto puede ser en una nueva columna o en la misma columna.

In [25]:
s_adop.apply( unidecode )

0                        Reporte Semestral de Adopcion
1                                               Periodo
2                     Institucion Encargada del Tramite
3                                 Solicitudes Recibidas
4                               Solicitudes  en Tramite
5     Solicitudes de adopcion con resolucion sobre l...
6     Solicitudes de adopcion con resolucion sobre l...
7                                 Adopciones concluidas
8                                              Femenino
9                                            Masculino
10                         Ninas de 0 - 4 anos 11 meses
11                         Ninas de \n5-8 anos 11 meses
12        Ninas y adolescentes mujeres de  \n9 -18 anos
13                                       Total de Ninas
14                         Ninos de 0 - 4 anos 11 meses
15                          Ninos de  5-8 anos 11 meses
16          Ninos y adolescentes hombre de 9 - 13 anos
17        Ninos y adolescentes hombres de 14 - 18 anos
18                                       Total de Ninos
19                                    Estado de Origen
20                                   Estado de Receptor
dtype: object

El aplicar la función `unidecode()` a la columna puede generar un error si hay `nan`s `AttributeError: 'float' object has no attribute 'encode'`. 
Esto se debe a que la columna incluye valores vacíos, los cuales son de tipo `float`, por lo tanto, la función `unidecode` falla, ya que los números no tienen acentos.

Dejo aquí una posible solución. Esta solución utiliza funciones lambda, las cuales son un tema avanzado más allá de este tutorial.

In [26]:
# sustituye unidecode por la función que quieres usar
df['Nombres_propios'].apply( lambda s: unidecode(s) if type(s)==str  else s )

ID
BO_1968_00001      teresa
BO_1968_00002    catalina
BO_1968_00003        juan
BO_1968_00004       isaac
BO_1968_00005         ma.
                   ...
BO_1982_07489         NaN
BO_1982_07490         NaN
BO_1982_07491         NaN
BO_1982_07492         NaN
BO_1982_07493         NaN
Name: Nombres_propios, Length: 96844, dtype: object

### Espacios

Otra posible limpieza es quitar espacios al principio y final del texto, o cambiar tabuladores, saltos de página o múltiples espacios por uno solo. 
Este tipo de ocurrencias son difíciles de ver en el texto como humanos; sin embargo, un espacio adicional al final de una palabra es suficiente para volverla un string diferente para la computadora. Por ejemplo, veamos este texto que incluye múltiples espacios, tabuladores y saltos de línea.

In [27]:
texto = "  Emanuel\tJurado     Sánchez \n "
print(texto)

  Emanuel	Jurado     Sánchez

La función `.strip()` quita los espacios adicionales del principio y final de un string.

In [28]:
print(texto.strip())

Emanuel	Jurado     Sánchez

Otra opción es combinar la función `.split()` y `.join()`.
La función `.split()` separa un texto en una lista, por default hace esto en los caracteres de espacio, pero se le pueden dar instrucciones de separar en caracteres específicos, por ejemplo en una coma `,`.
La función  `str.join()` une una lista con un carácter específico para generar un solo string.

En este caso estamos separando el texto en los espacios, para convertirlo en una lista de palabras. Después, esta lista se une con espacios.

In [29]:
texto.split()

['Emanuel', 'Jurado', 'Sánchez']

In [30]:
print(   ' '.join( texto.split() )   )

Emanuel Jurado Sánchez

### Funciones de limpieza de texto

Es común que una limpieza requiera varios pasos. Cómo hemos visto podemos aplicar varias funciones juntas.

In [31]:
s_adop.str.title().str.strip().apply(unidecode)

0                         Reporte Semestral De Adopcion
1                                               Periodo
2                     Institucion Encargada Del Tramite
3                                 Solicitudes Recibidas
4                               Solicitudes  En Tramite
5     Solicitudes De Adopcion Con Resolucion Sobre L...
6     Solicitudes De Adopcion Con Resolucion Sobre L...
7                                 Adopciones Concluidas
8                                              Femenino
9                                             Masculino
10                         Ninas De 0 - 4 Anos 11 Meses
11                         Ninas De \n5-8 Anos 11 Meses
12        Ninas Y Adolescentes Mujeres De  \n9 -18 Anos
13                                       Total De Ninas
14                         Ninos De 0 - 4 Anos 11 Meses
15                          Ninos De  5-8 Anos 11 Meses
16           Ninos Y Adolescentes Hombre De 9 - 13 Anos
17         Ninos Y Adolescentes Hombres De 14 - 18 Anos
18                                       Total De Ninos
19                                     Estado De Origen
20                                   Estado De Receptor
dtype: object

Una opción es definir una función que incluya todos los pasos.

In [32]:
def limpiar_texto(s:str, capitalize:str=None, dic_replace:dict=None):
    if type(s)==str: # checar el tipo
        # esto solo se ejecutará si es un string
        if dic_replace!=None: # sustituir substrings
            for k,v in dic_replace.items():
                s = s.replace(k,v)
        s = ' '.join( s.split() ) #quitar espacios extra
        s = unidecode(s) #quitar acentos
        if capitalize!=None: # cambiar capitalizacion
            if capitalize=='upper':  s = s.upper()
            elif capitalize=='lower':  s = s.lower()
            elif capitalize=='title':  s = s.title()
            elif capitalize=='capitalize':  s = s.capitalize()
    return s

texto = "  Emanuel\tJurado     Sánchez \n "
limpiar_texto(texto, capitalize='lower', dic_replace={'ez':'es'})

'emanuel jurado sanches'

Ahora aplicaremos la función en las columnas de interes.

In [33]:
s_adop.apply( limpiar_texto, capitalize='capitalize', dic_replace={' - ':'-', ' -':'-'} )

0                         Reporte semestral de adopcion
1                                               Periodo
2                     Institucion encargada del tramite
3                                 Solicitudes recibidas
4                                Solicitudes en tramite
5     Solicitudes de adopcion con resolucion sobre l...
6     Solicitudes de adopcion con resolucion sobre l...
7                                 Adopciones concluidas
8                                              Femenino
9                                             Masculino
10                           Ninas de 0-4 anos 11 meses
11                           Ninas de 5-8 anos 11 meses
12            Ninas y adolescentes mujeres de 9-18 anos
13                                       Total de ninas
14                           Ninos de 0-4 anos 11 meses
15                           Ninos de 5-8 anos 11 meses
16             Ninos y adolescentes hombre de 9-13 anos
17           Ninos y adolescentes hombres de 14-18 anos
18                                       Total de ninos
19                                     Estado de origen
20                                   Estado de receptor
dtype: object

## 6.e Limpieza de categóricos

En general se considera que un dato es categórico cuando hay pocas posibilidades definidas. Una aproximación rápida es que tenga menos de diez opciones de texto. Sin embargo, esta no es una regla dura, por ejemplo, el catálogo del INEGI de Estados, Municipios y Localidades tiene miles de opciones.


En este conjunto las columnas categóricas son:
* 'Sexo'
* 'Tipo_restos'
* 'Conocido_desconocido'

Además, nos interesa estandarizar algunas columnas para poder tratarlas cómo categóricos:
* 'Procedencia_transcrito'
* 'Diagnostico_transcrito'

In [34]:
col_cat = ['Sexo', 'Tipo_restos', 'Conocido_desconocido']

for col in col_cat:
    print(col)
    display( df[col].unique() )

Sexo

array(['Femenino', 'Masculino', 'S-D'], dtype=object)

Tipo_restos

array(['Cadáver', 'Miembros', 'Feto', 'Restos óseos', 'Recién nacido'],
      dtype=object)

Conocido_desconocido

array(['conocido', 'desconocido', 'S-D'], dtype=object)

El `dtype category` de pandas es un tipo de datos optimizado para variables categóricas, como clasificaciones o etiquetas repetitivas. Se distingue de otros tipos porque almacena los valores como referencias a una lista de categorías únicas, por lo que no solo es posible usar los valores válidos de la categoría. Además, permite definir un orden específico en las categorías, útil para comparaciones y ordenamientos.

Podemos convertir una columna de tipo `object` a `category` con la función `.astype("category")`.

In [35]:
df['Sexo'] = df['Sexo'].astype("category")
df['Sexo'].head()

ID
BO_1968_00001     Femenino
BO_1968_00002     Femenino
BO_1968_00003    Masculino
BO_1968_00004    Masculino
BO_1968_00005     Femenino
Name: Sexo, dtype: category
Categories (3, object): ['Femenino', 'Masculino', 'S-D']

Podemos ver que el tipo ha cambiado.

Dado que `category` limita los valores permitidos, es importante estandarizar los datos antes de cambiar el tipo de datos.

In [36]:
df['Conocido_desconocido'] = df['Conocido_desconocido'] \
                                .replace( {'conocido':'Conocido', 'desconocido':'Desconocido'} ) \
                                .astype("category")
df['Conocido_desconocido'].head()

ID
BO_1968_00001    Conocido
BO_1968_00002    Conocido
BO_1968_00003    Conocido
BO_1968_00004    Conocido
BO_1968_00005    Conocido
Name: Conocido_desconocido, dtype: category
Categories (3, object): ['Conocido', 'Desconocido', 'S-D']

Los datos con baja frecuencia pueden complicar el análisis y la visualización. En general se recomienda tratar los conjuntos que representen menos del 1% de los datos. Una estrategia común es agruparlos en un conjunto de 'Otros'.

In [37]:
df['Tipo_restos'].value_counts(normalize=True, dropna=False)

Tipo_restos
Cadáver          0.942278
Feto             0.029367
Miembros         0.021323
Recién nacido    0.006536
Restos óseos     0.000496
Name: proportion, dtype: float64

En este caso agruparemos los restos óseos con los miembros.

In [38]:
df['Tipo_restos'] = df['Tipo_restos'].replace( {'Miembros':'Miembros u óseos',  'Restos óseos':'Miembros u óseos'} )
df['Tipo_restos'].value_counts(normalize=True, dropna=False)

Tipo_restos
Cadáver             0.942278
Feto                0.029367
Miembros u óseos    0.021819
Recién nacido       0.006536
Name: proportion, dtype: float64

Una ventaja de usar `category` es que permite definir un orden diferente al alfabético o numérico. Por ejemplo, definamos un orden especial para el tipo de restos. Por defecto, las categorías se ordenan alfabéticamente, pero esto se puede modificar.

In [39]:
from pandas.api.types import CategoricalDtype

orden_restos = ['Cadáver', 'Feto', 'Recién nacido', 'Miembros u óseos']
orden_restos = CategoricalDtype(categories=orden_restos, ordered=True)
df['Tipo_restos'] = df['Tipo_restos'].astype( orden_restos )
df['Tipo_restos'].tail()

ID
BO_1982_07489    Miembros u óseos
BO_1982_07490    Miembros u óseos
BO_1982_07491    Miembros u óseos
BO_1982_07492    Miembros u óseos
BO_1982_07493             Cadáver
Name: Tipo_restos, dtype: category
Categories (4, object): ['Cadáver' < 'Feto' < 'Recién nacido' < 'Miembros u óseos']

Ahora si ordenamos el dataframe se usará el orden especial qué hemos definido

In [40]:
df[['Sexo', 'Tipo_restos']].sort_values(by='Tipo_restos').drop_duplicates()

                    Sexo       Tipo_restos
ID
BO_1968_00001   Femenino           Cadáver
BO_1978_04191  Masculino           Cadáver
BO_1978_05479        S-D           Cadáver
BO_1975_06609  Masculino              Feto
BO_1972_02154        S-D              Feto
BO_1977_06761   Femenino              Feto
BO_1980_07447  Masculino     Recién nacido
BO_1975_06672   Femenino     Recién nacido
BO_1970_05061        S-D     Recién nacido
BO_1982_07388  Masculino  Miembros u óseos
BO_1980_07582   Femenino  Miembros u óseos
BO_1972_03749        S-D  Miembros u óseos

### Catálogos por similitud

A veces es necesario estandarizar los datos antes de volverlos una categoría.

Por ejemplo, esta serie de datos está basada en datos llenados a mano sobre el sexo de pacientes.

In [41]:
s_sexo = pd.Series( [' Masculino', '-', '?', 'F', 'Femenina', 'Femenino', 'Femenino y Masculino', 'I?','Ilegible', 
                         'Indeterminable', 'Indeterminado', 'M', 'M F', 'MAsculino', 'Maculino', 'Masculino', 'Masculino.', 
                         'N', 'S/D', 'femenina', 'femenino', 'ilegible', 'indeterminado', 'masculino', 's/d', 'sin dato' ] ) 
s_sexo

0                Masculino
1                        -
2                        ?
3                        F
4                 Femenina
5                 Femenino
6     Femenino y Masculino
7                       I?
8                 Ilegible
9           Indeterminable
10           Indeterminado
11                       M
12                     M F
13               MAsculino
14                Maculino
15               Masculino
16              Masculino.
17                       N
18                     S/D
19                femenina
20                femenino
21                ilegible
22           indeterminado
23               masculino
24                     s/d
25                sin dato
dtype: object

En primer lugar, tenemos que determinar cuáles opciones incluir en el catálogo. Además, es necesario tomar decisiones de registros dobles como 'M F'. 
En este caso nos gustaría reducir las opciones a 'Femenino', 'Masculino' e 'Indeterminado', donde 'Indeterminado' incluirá todos los casos donde haya duda.

Para lograr la estandarización se genera un diccionario de equivalencias, el cual se usa con la función `.replace()` o `.map()`.  Las funciones `.replace()` y `.map()` toman un diccionario y lo utilizan para remplazar los valores. Sin embargo, `.replace()` solo sustituye los valores en el diccionario y, si el valor en la serie no está en las llaves del diccionario, deja el valor original. Por otro lado, `.map()` cambia todos los valores en el diccionario y si no se encuentran el diccionario lo sustituye por `nan`, por lo cual es útil para filtrar valores no válidos.

Este diccionario se puede escribir a mano cómo se hizo arriba o inferir. Existen varias técnicas para limpiar este tipo de datos, incluyendo usar AI generativa. Cada técnica tiene sus ventajas y desventajas.

En este caso usaremos `wibblywobbly`, esta biblioteca toma un catálogo y un conjunto de datos y regresa que tanto se parecen los textos. Revisen la documentación en: [https://github.com/mar-esther23/WibblyWobbly](https://github.com/mar-esther23/WibblyWobbly).

In [42]:
# !pip install thefuzz wibblywobbly
import wibblywobbly as ww

cat_sexo = ['Femenino', 'Masculino', 'Indeterminado']
ww.map_list_to_catalog(s_sexo, cat_sexo)

WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

,Data,Option1,Score1,Option2,Score2,Option3,Score3
0,masculino,Masculino,100,None,NaN,None,NaN
1,indeterminado,Indeterminado,100,None,NaN,None,NaN
2,femenino,Femenino,100,None,NaN,None,NaN
3,Masculino.,Masculino,100,None,NaN,None,NaN
4,Masculino,Masculino,100,None,NaN,None,NaN
5,MAsculino,Masculino,100,None,NaN,None,NaN
6,Indeterminado,Indeterminado,100,None,NaN,None,NaN
7,Femenino,Femenino,100,None,NaN,None,NaN
8,Masculino,Masculino,100,None,NaN,None,NaN
9,Maculino,Masculino,94,None,NaN,None,NaN
10,Femenino y Masculino,Masculino,90,None,NaN,None,NaN
11,femenina,Femenino,88,Indeterminado,56.0,Masculino,35.0
12,Femenina,Femenino,88,Indeterminado,56.0,Masculino,35.0
13,Indeterminable,Indeterminado,81,Femenino,45.0,Masculino,34.0
14,sin dato,sin dato,0,None,NaN,None,NaN
15,s/d,s/d,0,None,NaN,None,NaN
16,ilegible,ilegible,0,None,NaN,None,NaN
17,S/D,S/D,0,None,NaN,None,NaN
18,N,N,0,None,NaN,None,NaN
19,M F,M F,0,None,NaN,None,NaN
20,M,M,0,None,NaN,None,NaN
21,Ilegible,Ilegible,0,None,NaN,None,NaN
22,I?,I?,0,None,NaN,None,NaN
23,F,F,0,None,NaN,None,NaN
24,?,?,0,None,NaN,None,NaN
25,-,-,0,None,NaN,None,NaN

También es posible obtener directamente un diccionario de sustitución.

La opción `reject_value` permite establecer un valor default si no se encuentra un texto lo suficientemente similar en el catálogo.

In [43]:
sexo_replace = ww.map_list_to_catalog(s_sexo, cat_sexo, output_format="dictionary", reject_value='Indeterminado')
sexo_replace

WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']
WARNING:thefuzz.process:Applied processor reduces input query to empty string, all comparisons will have score 0. [Query: '']

{'F': 'Indeterminado',
 'M F': 'Indeterminado',
 'S/D': 'Indeterminado',
 's/d': 'Indeterminado',
 'M': 'Indeterminado',
 'Femenino y Masculino': 'Masculino',
 'femenina': 'Femenino',
 'ilegible': 'Indeterminado',
 'Indeterminado': 'Indeterminado',
 '-': 'Indeterminado',
 ' Masculino': 'Masculino',
 'Masculino.': 'Masculino',
 'N': 'Indeterminado',
 'masculino': 'Masculino',
 'Femenina': 'Femenino',
 '?': 'Indeterminado',
 'Maculino': 'Masculino',
 'Ilegible': 'Indeterminado',
 'Indeterminable': 'Indeterminado',
 'sin dato': 'Indeterminado',
 'MAsculino': 'Masculino',
 'indeterminado': 'Indeterminado',
 'Masculino': 'Masculino',
 'femenino': 'Femenino',
 'Femenino': 'Femenino',
 'I?': 'Indeterminado'}

Este diccionario tiene errores, los cuales se pueden arreglar manualmente.

In [44]:
sexo_replace['M'] = 'Masculino'
sexo_replace['F'] = 'Femenino'
sexo_replace['Femenino y Masculino'] = 'Indeterminado'

sexo_replace

{'F': 'Femenino',
 'M F': 'Indeterminado',
 'S/D': 'Indeterminado',
 's/d': 'Indeterminado',
 'M': 'Masculino',
 'Femenino y Masculino': 'Indeterminado',
 'femenina': 'Femenino',
 'ilegible': 'Indeterminado',
 'Indeterminado': 'Indeterminado',
 '-': 'Indeterminado',
 ' Masculino': 'Masculino',
 'Masculino.': 'Masculino',
 'N': 'Indeterminado',
 'masculino': 'Masculino',
 'Femenina': 'Femenino',
 '?': 'Indeterminado',
 'Maculino': 'Masculino',
 'Ilegible': 'Indeterminado',
 'Indeterminable': 'Indeterminado',
 'sin dato': 'Indeterminado',
 'MAsculino': 'Masculino',
 'indeterminado': 'Indeterminado',
 'Masculino': 'Masculino',
 'femenino': 'Femenino',
 'Femenino': 'Femenino',
 'I?': 'Indeterminado'}

Ahora podemos remplazar, estandarizar y contar.

In [45]:
s_sexo = s_sexo.replace( sexo_replace )
s_sexo

0         Masculino
1     Indeterminado
2     Indeterminado
3          Femenino
4          Femenino
5          Femenino
6     Indeterminado
7     Indeterminado
8     Indeterminado
9     Indeterminado
10    Indeterminado
11        Masculino
12    Indeterminado
13        Masculino
14        Masculino
15        Masculino
16        Masculino
17    Indeterminado
18    Indeterminado
19         Femenino
20         Femenino
21    Indeterminado
22    Indeterminado
23        Masculino
24    Indeterminado
25    Indeterminado
dtype: object

In [46]:
s_sexo.value_counts(dropna=False)

Indeterminado    14
Masculino         7
Femenino          5
Name: count, dtype: int64

### Estandarización con tablas

En algunos casos es necesario generar una tabla con equivalencias e información extra.

Por ejemplo, hay múltiples formas de escribir una misma procedencia. La Coordinación 1 de Cuauhtémoc aparece cómo '1a', 'CH-1', etc. Además, hay casos donde los ingresos provienen de múltiples procedencias, cómo '33a+1a' o 'C-I HX'. En este caso es necesario hacer procesos de limpieza complejos que requieren revisión manual. El resultado de ese proceso es la tabla `cat_proc_sustitucion.xlsx`.

In [47]:
df_proc = pd.read_csv('data_raw/cat_proc_sustitucion.csv')
df_proc.tail()

,Procedencia_transcrito,Procedencia_estandar,Procedencia_extendido,Freq,Npartes,Nfalta,IDs,Procedencia_alcaldia
840,C-A,NaN,NaN,1,1,0,BO_1976_06416,NaN
841,C-2,NaN,NaN,1,1,0,BO_1975_04183,NaN
842,C,NaN,NaN,1,1,0,BO_1975_05458,NaN
843,C. R. Cela,NaN,NaN,1,1,0,BO_1971_01331,NaN
844,C-X-1,NaN,NaN,1,1,0,BO_1975_01317,NaN

Esta unión es muchos a uno, ya que una procedencia puede estar múltiples veces en el HBO pero solo una vez en el catálogo de procedencias. Por lo tanto, uniremos la tabla usando `.merge()` y la opción `how='left'`.

Nota: `.merge()` puede reescribir el índice de la tabla, por lo que lo volveremos columna antes de iniciar el proceso para conservarlo.

In [48]:
df = df.reset_index() # conserva indice
cols = ['Procedencia_transcrito','Procedencia_estandar','Procedencia_extendido','Procedencia_alcaldia']
df = df.merge(df_proc[cols], how='left', on='Procedencia_transcrito')
df[['ID'] +cols]

,ID,Procedencia_transcrito,Procedencia_estandar,Procedencia_extendido,Procedencia_alcaldia
0,BO_1968_00001,S-D,S-D,Sin datos,NaN
1,BO_1968_00002,S-D,S-D,Sin datos,NaN
2,BO_1968_00003,S-D,S-D,Sin datos,NaN
3,BO_1968_00004,S-D,S-D,Sin datos,NaN
4,BO_1968_00005,S-D,S-D,Sin datos,NaN
...,...,...,...,...,...
96839,BO_1982_07489,15a,GAM-2,Coord Territorial 2 Gustavo A Madero (Col Arag...,Gustavo A Madero
96840,BO_1982_07490,32a,COY-2,Coord Territorial 2 Coyoacan (Col Romero de Te...,Coyoacan
96841,BO_1982_07491,32a,COY-2,Coord Territorial 2 Coyoacan (Col Romero de Te...,Coyoacan
96842,BO_1982_07492,27a,XO-2,Coord Territorial 2 Xochimilco (Barrio de San ...,Xochimilco
96843,BO_1982_07493,9a,MH-1,Coord Territorial 1 Miguel Hidalgo – Hospital ...,Miguel Hidalgo

A continuación haremos varios pasos extra de limpieza. Cómo estás columnas son principalmente para el análisis sustituiremos los 'S-D' por `nan`. Además, volveremos las columnas categóricas.

In [49]:
cols = ['Procedencia_estandar','Procedencia_extendido']
df[cols] = df[cols].replace({'S-D':nan, 'Sin datos':nan})
    
df['Procedencia_estandar'] = df['Procedencia_estandar'].astype("category")
df['Procedencia_alcaldia'] = df['Procedencia_alcaldia'].astype("category")

df[cols].value_counts(dropna=False).head(10)

Procedencia_estandar  Procedencia_extendido
NaN                   NaN                                                           25889
HB                    Hospital Balbuena (Col Jardin Balbuena)                        5441
CR                    Cruz Roja (Col Polanco)                                        4875
GAM-2                 Coord Territorial 2 Gustavo A Madero (Col Aragon La Villa)     4107
COY-2                 Coord Territorial 2 Coyoacan (Col Romero de Terreros)          3635
CUH-1                 Coord Territorial 1 Cuauhtemoc (Col San Simon Tolnahuac)       3585
HX                    Hospital Xoco (Col General Anaya)                              3576
HV                    Hospital la Villa (Col Granjas Modernas)                       3508
HGRL                  Hospital Ruben Leñero (Col Santo Tomas)                        2975
CUH-6                 Coord Territorial 6 Cuauhtemoc (Col Centro)                    2312
Name: count, dtype: int64

Repetiremos el mismo procedimiento para los diagnósticos.

In [50]:
df_diag = pd.read_csv('data_raw/cat_diag_sustitucion.csv')
df_diag.tail()

,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Freq,Npartes,Nfalta,IDs,Diagnostico_clasificacion
3220,Tipo isquemia Lesiones Vasculares,Vascu,vascular,1,4,3,BO_1975_06755,NaN
3221,VE,VE,varices esofagicas,8,1,0,"BO_1974_02294,BO_1974_05027,BO_1975_05081,BO_1...",Enfermedades del sistema digestivo
3222,VE+CHAN,VE,varices esofagicas,2,2,1,"BO_1974_03952,BO_1974_04426",Enfermedades del sistema digestivo
3223,VE+,VE,varices esofagicas,2,1,0,"BO_1977_00795,BO_1977_00868",Enfermedades del sistema digestivo
3224,CE+VE,VE,varices esofagicas,1,2,1,BO_1977_02642,Enfermedades del sistema digestivo

In [51]:
cols = ['Diagnostico_transcrito','Diagnostico_estandar','Diagnostico_extendido','Diagnostico_clasificacion']
df = df.merge(df_diag[cols], how='left', on='Diagnostico_transcrito')
df[['ID'] +cols]

,ID,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Diagnostico_clasificacion
0,BO_1968_00001,S-D,S-D,sin datos,NaN
1,BO_1968_00002,S-D,S-D,sin datos,NaN
2,BO_1968_00003,S-D,S-D,sin datos,NaN
3,BO_1968_00004,S-D,S-D,sin datos,NaN
4,BO_1968_00005,S-D,S-D,sin datos,NaN
...,...,...,...,...,...
96839,BO_1982_07489,S-D,S-D,sin datos,NaN
96840,BO_1982_07490,S-D,S-D,sin datos,NaN
96841,BO_1982_07491,S-D,S-D,sin datos,NaN
96842,BO_1982_07492,S-D,S-D,sin datos,NaN
96843,BO_1982_07493,S-D,S-D,sin datos,NaN

In [52]:
cols = ['Diagnostico_estandar','Diagnostico_extendido']
df[cols] = df[cols].replace({'S-D':nan, 'sin datos':nan})

df['Diagnostico_estandar'] = df['Diagnostico_estandar'].astype("category")
df['Diagnostico_clasificacion'] = df['Diagnostico_clasificacion'].astype("category")

df[cols].value_counts(dropna=False).head(10)

Diagnostico_estandar  Diagnostico_extendido
NaN                   NaN                                 56552
TM                    traumatismo multiple                 7551
TCE                   traumatismo craneo encefalico        6045
BN                    bronconeumonia                       2007
CVG                   congestion visceral generalizada     1349
TCT                   traumatismo craneo torax             1189
HPAF                  herida arma fuego                    1008
HPAFC                 herida arma fuego craneo              950
Dispensa              dispensa                              925
Quem                  quemaduras                            844
Name: count, dtype: int64

Revisemos los tipos de datos de nuestra tabla. Además, es buena idea recalcular el profile de datos y revisar los cambios hechos hasta ahora.

In [53]:
df.columns

Index(['ID', 'Nombre_completo_transcrito', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha_transcrito',
       'Procedencia_transcrito', 'Diagnostico_transcrito', 'Sexo',
       'Edad_transcrito', 'Tipo_restos', 'Conocido_desconocido',
       'Procedencia_estandar', 'Procedencia_extendido', 'Procedencia_alcaldia',
       'Diagnostico_estandar', 'Diagnostico_extendido',
       'Diagnostico_clasificacion'],
      dtype='object')

In [54]:
df = df[['ID', 'Nombre_completo_transcrito', 'Primer_apellido',
         'Segundo_apellido', 'Nombres_propios', 'Fecha_transcrito',
         'Procedencia_transcrito', 'Procedencia_estandar', 'Procedencia_extendido', 'Procedencia_alcaldia',
         'Diagnostico_transcrito', 'Diagnostico_estandar', 'Diagnostico_extendido', 'Diagnostico_clasificacion',
         'Sexo', 'Edad_transcrito', 'Tipo_restos', 'Conocido_desconocido',
         ]]
df.dtypes

ID                              object
Nombre_completo_transcrito      object
Primer_apellido                 object
Segundo_apellido                object
Nombres_propios                 object
Fecha_transcrito                object
Procedencia_transcrito          object
Procedencia_estandar          category
Procedencia_extendido           object
Procedencia_alcaldia          category
Diagnostico_transcrito          object
Diagnostico_estandar          category
Diagnostico_extendido           object
Diagnostico_clasificacion     category
Sexo                          category
Edad_transcrito                 object
Tipo_restos                   category
Conocido_desconocido          category
dtype: object

In [55]:
from ydata_profiling import ProfileReport

file_profile = "profiles/HBO_profile_clean.html"
prof = ProfileReport( df ) 
prof.to_file(output_file=file_profile)

/home/esther/anaconda3/envs/CursoPandas2025/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Summarize dataset: 100%|█████████████| 28/28 [00:04<00:00,  6.26it/s, Completed]
Generate report structure: 100%|██████████████████| 1/1 [00:03<00:00,  3.47s/it]
Render HTML: 100%|████████████████████████████████| 1/1 [00:00<00:00,  3.30it/s]
Export report to file: 100%|█████████████████████| 1/1 [00:00<00:00, 135.71it/s]

## 6.f Limpieza de números

Existen dos tipos de datos numéricos, enteros y flotantes. Los dos se comportan de forma muy similar.
En este conjunto de datos, la columna `Edad_transcrito` contiene números; sin embargo, su tipo es `object`, ya que hay edades como '6 días' o algunas que incluyen posibles errores cómo '-48' o ' S-D'. Además, incluso los números están cómo `str` debido a que procesamos la variable.

In [56]:
df['Edad_transcrito'].unique()

array(['S-D', ' S-D', '6 dias', '16 días', '30 dias', '4 meses',
       '3 meses', '14 dias', '18 dias', '3 semanas', '2 meses', '63',
       '17', '69', '40', '68', '50', '42', '66', '55', '60', '30', '48',
       '39', '35', '37', '56', '62', '27', '4', '41', '25', '72', '16',
       '65', '26', '8', '20', '3m', '3a', '28', '58', '23', '22', '4a',
       '75', '19m', '24', '14m', '54', '19', '34', '80', '13', '36', '45',
       '2', '61', '12', '70', '49', '1', '95', '3', '33', '32', '10 días',
       '14', '57', '85', '16M', '21', '5', '74', '7', '15', '6', '86',
       '11', '18m', '47', '29', '52', '81', '84', '18', '38', '43', '53',
       '1.5', '9m', '2m', '9', '44', '64', '73', '82', '83', '6m', '4m',
       '51', '8 días', '77', '10', '31', '46', '8 meses', '59',
       '18 meses', '25 dias', '20 meses', '6 meses', '79', '9 meses',
       '71', '67', '78', '1 mes', '90', '76', '5 meses', '2 meses ',
       '20 días', '14 meses', '98', '11 días', '3meses', '93', '15 días',
       '11 meses', '3.5', '10 meses', '87', '15  días', '12  días',
       '21  días', '88', '10 SEMNS', '40  días', '7 meses', '3  días',
       '89', '94', '72 horas', '5  días', '4.5', '1 Y 8 meses',
       '15 meses', '48  días', '16 meses', '22 meses', '?', '13  días',
       '1 meses', '1  días', '26 dias', '45  días', '92', '[8]', '4 dias',
       '1 MES', '6  días', '3 días', '19 días', '2.5', '103', '6 días',
       '17 días', '1 día', '30 días', '4 días', '7 días', '7.5',
       '13 días', '22 días', '25 días', '12 días', '6.5 meses',
       '3.5 meses', '5.5 meses', '4.5 meses', '50 horas', '2 días',
       '24 horas', '91', '1 año 4 meses', '9 días', '96', '40 días', '97',
       '102', '41 días', '1,5', '1 año 3 meses', '7,5', '1.3 meses',
       '1.5 meses', '21 días', '2,5', '100', '-12 horas', '5 días',
       '45 días', '36 días', '25-30', '8.5', '5.5', ' +6-8', ' +7-9',
       '4 y 5', ' +3-4', ' +4-6', ' +3-5', ' +5-6', ' +2-3', ' +4-7',
       ' +7-8', '6.5', ' +5-7', '32 semanas', '-72', '28 semanas',
       ' +6-7', '4 meses ', '2 Meses ', '5 Meses ', '11 Meses',
       '18 Meses', 'F', '3 Meses', '1 1/2 Años', '2 Meses', '4 Meses',
       '18 meses ', '16 días ', '46 días', '9 Meses', '30 Meses',
       '18 Meses ', '3 meses ', '2.5 años ', '8 meses ', '1.5 años',
       '2.5 meses', '11 meses ', '6 meses ', '3.5 años', '10 días ',
       '17 meses', '2.5 años', '17 días ', '10 meses ', '53 días ',
       '[1-10 días]', '12 meses', '27 días ', '15 días ', '20 días ',
       '99', '5 días ', '19 meses', '4.5 años', '42 días', '1.5 años ',
       '7.5 meses', '28.2', '8.3', '2.2', '29.1', '25.1', '13.2', '5.3',
       '27.1', '8.2', '13A', '18.2', '18A', '24.2', '23.2', '3.2',
       '27 dias', '15 dias', '6M', '3M', '1A', '2 dias', '10 dias', '5M',
       '3 dias', '25-40', '6 semanas', '7 dias', '20 dias', '1 dia',
       '20 o 24', '10 semanas', '18 semanas', '6 semanas ', '-48', '-78',
       'S-d', '28 días', '2 años', '2 1/2a', '3 1/2', '6a', '12a', '7a',
       '2 1/2', '8 dias', '12 dias', '24 dias', '13 meses', '72 hrs',
       '5 dias', '30 meses', '17 dias', '-', '23 meses', '28 dias',
       '9 dias', ' 8 meses', '15 mese', '11 dias', '40 dias',
       '3 años y medio ', '6 dias ', '18 m', '3 m', '14 días', '1 1/2',
       '8 1/2 meses', '15a', '1d', '15d', '5a', '24d', '1 1/2a', '13a',
       '6 1/2m', '4M', '17a', '5d', '6d', '1a', '8m', '16a', '8d', '3d',
       '45d', '14a', '25/30', '7 1/2', '19d', '17d', '7d', '10a', '30d',
       '21d', '2 1/2 m', '5m', '16d', '2a', '6 1/2', '20 semanas', '5-7',
       '4 1/2', '5 1/2', '8 1/2', '5 semanas', '1 1/2 meses', '7 - 9',
       '2 semanas', '8 Ins.', '3 años', '6 años', '9 años', '12 años',
       '17 años', '1 año', '13 años', '5 años', '4 años', '18 años',
       '65 meses', '7 años', '8 años', '2/6', '10 años', '11 años',
       '5  años', '16 años', '15 años', '14 años', '1 años', '19 años',
       '8 años7', '7 - 12 meses', '108', '1 - 3', '2años', '30 - 90 días',
       '15-30 días', '12 horas', '7 añoss', '2 o 3 meses', '26 meses',
       '1 año 7 meses', 'más 72', '5 meses 15 días', 'M', '-72 h',
       '73 días', '4-6', '7-9', '1-2', '9-9', '3-4', '7-8', '2-4', '6-8',
       '-12', '6 meses UI', '24 días', '$45', '2 1/2 a', '0', '9 a',
       '1 1/2 a', '2 m', '8 semanas', '41 n', '81a', '18 mese', '2 mese',
       '13 dias', 'R.N', '116', '107', '19 dias', '47 dias', '8a',
       '50 dias', '39 meses', '18-25', '8 172', '3-5', '16 semanas',
       '35 semanas'], dtype=object)

Lo primero es hacer una copia de la columna con los textos limpios, la cual llamaremos 'Edad_str'. Aprovecharemos para sustituir 'S-D' por `nan`.

In [57]:
df['Edad_str'] = df['Edad_transcrito'].apply( limpiar_texto, capitalize='lower' )
df['Edad_str'] = df['Edad_str'].replace('s-d',nan)
df['Edad_str'].unique()

array([nan, '6 dias', '16 dias', '30 dias', '4 meses', '3 meses',
       '14 dias', '18 dias', '3 semanas', '2 meses', '63', '17', '69',
       '40', '68', '50', '42', '66', '55', '60', '30', '48', '39', '35',
       '37', '56', '62', '27', '4', '41', '25', '72', '16', '65', '26',
       '8', '20', '3m', '3a', '28', '58', '23', '22', '4a', '75', '19m',
       '24', '14m', '54', '19', '34', '80', '13', '36', '45', '2', '61',
       '12', '70', '49', '1', '95', '3', '33', '32', '10 dias', '14',
       '57', '85', '16m', '21', '5', '74', '7', '15', '6', '86', '11',
       '18m', '47', '29', '52', '81', '84', '18', '38', '43', '53', '1.5',
       '9m', '2m', '9', '44', '64', '73', '82', '83', '6m', '4m', '51',
       '8 dias', '77', '10', '31', '46', '8 meses', '59', '18 meses',
       '25 dias', '20 meses', '6 meses', '79', '9 meses', '71', '67',
       '78', '1 mes', '90', '76', '5 meses', '20 dias', '14 meses', '98',
       '11 dias', '3meses', '93', '15 dias', '11 meses', '3.5',
       '10 meses', '87', '12 dias', '21 dias', '88', '10 semns',
       '40 dias', '7 meses', '3 dias', '89', '94', '72 horas', '5 dias',
       '4.5', '1 y 8 meses', '15 meses', '48 dias', '16 meses',
       '22 meses', '?', '13 dias', '1 meses', '1 dias', '26 dias',
       '45 dias', '92', '[8]', '4 dias', '19 dias', '2.5', '103',
       '17 dias', '1 dia', '7 dias', '7.5', '22 dias', '6.5 meses',
       '3.5 meses', '5.5 meses', '4.5 meses', '50 horas', '2 dias',
       '24 horas', '91', '1 ano 4 meses', '9 dias', '96', '97', '102',
       '41 dias', '1,5', '1 ano 3 meses', '7,5', '1.3 meses', '1.5 meses',
       '2,5', '100', '-12 horas', '36 dias', '25-30', '8.5', '5.5',
       '+6-8', '+7-9', '4 y 5', '+3-4', '+4-6', '+3-5', '+5-6', '+2-3',
       '+4-7', '+7-8', '6.5', '+5-7', '32 semanas', '-72', '28 semanas',
       '+6-7', 'f', '1 1/2 anos', '46 dias', '30 meses', '2.5 anos',
       '1.5 anos', '2.5 meses', '3.5 anos', '17 meses', '53 dias',
       '[1-10 dias]', '12 meses', '27 dias', '99', '19 meses', '4.5 anos',
       '42 dias', '7.5 meses', '28.2', '8.3', '2.2', '29.1', '25.1',
       '13.2', '5.3', '27.1', '8.2', '13a', '18.2', '18a', '24.2', '23.2',
       '3.2', '1a', '5m', '25-40', '6 semanas', '20 o 24', '10 semanas',
       '18 semanas', '-48', '-78', '28 dias', '2 anos', '2 1/2a', '3 1/2',
       '6a', '12a', '7a', '2 1/2', '24 dias', '13 meses', '72 hrs', '-',
       '23 meses', '15 mese', '3 anos y medio', '18 m', '3 m', '1 1/2',
       '8 1/2 meses', '15a', '1d', '15d', '5a', '24d', '1 1/2a', '6 1/2m',
       '17a', '5d', '6d', '8m', '16a', '8d', '3d', '45d', '14a', '25/30',
       '7 1/2', '19d', '17d', '7d', '10a', '30d', '21d', '2 1/2 m', '16d',
       '2a', '6 1/2', '20 semanas', '5-7', '4 1/2', '5 1/2', '8 1/2',
       '5 semanas', '1 1/2 meses', '7 - 9', '2 semanas', '8 ins.',
       '3 anos', '6 anos', '9 anos', '12 anos', '17 anos', '1 ano',
       '13 anos', '5 anos', '4 anos', '18 anos', '65 meses', '7 anos',
       '8 anos', '2/6', '10 anos', '11 anos', '16 anos', '15 anos',
       '14 anos', '1 anos', '19 anos', '8 anos7', '7 - 12 meses', '108',
       '1 - 3', '2anos', '30 - 90 dias', '15-30 dias', '12 horas',
       '7 anoss', '2 o 3 meses', '26 meses', '1 ano 7 meses', 'mas 72',
       '5 meses 15 dias', 'm', '-72 h', '73 dias', '4-6', '7-9', '1-2',
       '9-9', '3-4', '7-8', '2-4', '6-8', '-12', '6 meses ui', '$45',
       '2 1/2 a', '0', '9 a', '1 1/2 a', '2 m', '8 semanas', '41 n',
       '81a', '18 mese', '2 mese', 'r.n', '116', '107', '47 dias', '8a',
       '50 dias', '39 meses', '18-25', '8 172', '3-5', '16 semanas',
       '35 semanas'], dtype=object)

Volver la edad a número se puede hacer con la función `.to_numeric()` o con `.astype()`.
Los datos que no se pueden convertir a número, por ejemplo '18 semanas', ya que generarán error. La función tiene varios parámetros que nos pueden servir:
```
errors{‘ignore’, ‘raise’, ‘coerce’}, default ‘raise’
        If ‘raise’, then invalid parsing will raise an exception.
        If ‘coerce’, then invalid parsing will be set as NaN.
        If ‘ignore’, then invalid parsing will return the input.
```

Una primera aproximación es convertir obligar a que se convierta a número. Cómo los datos de semanas nos pueden ser útiles a futuro no vamos a rescribir la columna 'Edad', sino a generar una nueva columna 'Edad_int' con los resultados

In [58]:
df['Edad_int'] = pd.to_numeric(df['Edad_str'], errors="coerce")
df['Edad_int'].unique()

array([  nan,  63. ,  17. ,  69. ,  40. ,  68. ,  50. ,  42. ,  66. ,
        55. ,  60. ,  30. ,  48. ,  39. ,  35. ,  37. ,  56. ,  62. ,
        27. ,   4. ,  41. ,  25. ,  72. ,  16. ,  65. ,  26. ,   8. ,
        20. ,  28. ,  58. ,  23. ,  22. ,  75. ,  24. ,  54. ,  19. ,
        34. ,  80. ,  13. ,  36. ,  45. ,   2. ,  61. ,  12. ,  70. ,
        49. ,   1. ,  95. ,   3. ,  33. ,  32. ,  14. ,  57. ,  85. ,
        21. ,   5. ,  74. ,   7. ,  15. ,   6. ,  86. ,  11. ,  47. ,
        29. ,  52. ,  81. ,  84. ,  18. ,  38. ,  43. ,  53. ,   1.5,
         9. ,  44. ,  64. ,  73. ,  82. ,  83. ,  51. ,  77. ,  10. ,
        31. ,  46. ,  59. ,  79. ,  71. ,  67. ,  78. ,  90. ,  76. ,
        98. ,  93. ,   3.5,  87. ,  88. ,  89. ,  94. ,   4.5,  92. ,
         2.5, 103. ,   7.5,  91. ,  96. ,  97. , 102. , 100. ,   8.5,
         5.5,   6.5, -72. ,  99. ,  28.2,   8.3,   2.2,  29.1,  25.1,
        13.2,   5.3,  27.1,   8.2,  18.2,  24.2,  23.2,   3.2, -48. ,
       -78. , 108. , -12. ,   0. , 116. , 107. ])

Veamos las edades que no fueron convertidas por la operación:

In [59]:
df.loc[ (df['Edad_str'].notna()) & (df['Edad_int'].isna()), ['Tipo_restos','Edad_str','Edad_int'] ].drop_duplicates()

            Tipo_restos    Edad_str  Edad_int
16347           Cadáver      6 dias       NaN
26472     Recién nacido     16 dias       NaN
27520           Cadáver     30 dias       NaN
29285           Cadáver     4 meses       NaN
29497           Cadáver     3 meses       NaN
...                 ...         ...       ...
73823              Feto  35 semanas       NaN
73862     Recién nacido      5 dias       NaN
73863     Recién nacido     10 dias       NaN
73922  Miembros u óseos     9 meses       NaN
74042  Miembros u óseos    18 meses       NaN

[280 rows x 3 columns]

### Asignación de valores con base en otras variables

La mayor parte de las edades en semanas son de fetos y recién nacido. En el caso de los fetos y recién nacidos podemos suponer que la edad es cero. Sin embargo, solo debemos de hacer esa suposición en el caso de los que tienen una edad registrada, para evitar cambiar la distribución de la población. Para hacer esto se hará una selección doble y asignaremos el valor al subconjunto con `.loc[]`.

Primero veamos la distribución actual de la variable.

In [60]:
df['Edad_int'].value_counts(dropna=False).head(10)

Edad_int
NaN     59556
40.0     1728
30.0     1711
35.0     1666
25.0     1618
45.0     1581
50.0     1444
60.0     1252
20.0     1157
55.0     1047
Name: count, dtype: int64

Contemos la cantidad de `0` en este subconjunto, este es nuestro valor inicial.

In [61]:
(df['Edad_int']==0).sum()

np.int64(1)

Las celdas a convertir son aquellas que cumplen las condiciones:
* Existe un texto en 'Edad_str'
* El tipo es Feto o Recién nacido

In [62]:
row_fetorn = (df['Edad_str'].notna()) & (df['Tipo_restos'].isin(['Feto','Recién nacido']))
df.loc[row_fetorn,['Edad_str', 'Tipo_restos', 'Edad_int']]

      Edad_str    Tipo_restos  Edad_int
26472  16 dias  Recién nacido       NaN
34143       38           Feto      38.0
38134  9 meses           Feto       NaN
38135  6 meses           Feto       NaN
38136  7 meses           Feto       NaN
...        ...            ...       ...
73863  10 dias  Recién nacido       NaN
73864      -72  Recién nacido     -72.0
73865      -72  Recién nacido     -72.0
73866      -72  Recién nacido     -72.0
73867      -72  Recién nacido     -72.0

[1397 rows x 3 columns]

Contemos la cantidad de ceros en este subconjunto.

In [63]:
(df.loc[row_fetorn,'Edad_int']==0).sum()

np.int64(0)

Dado que:
* El subconjunto a editar mide 1397 filas (+1397)
* No hay `0` en el subconjunto (-0)
* Hay un `0` inicial (+1)
Esperamos un total de 1398 `0`s. 

Ahora asignemos una edad de cero a los fetos y recién nacidos y revisemos.

In [64]:
df.loc[row_fetorn, 'Edad_int'] = 0
df['Edad_int'].value_counts(dropna=False).head(15)

Edad_int
NaN     59087
40.0     1728
30.0     1710
35.0     1666
25.0     1618
45.0     1579
50.0     1444
0.0      1398
60.0     1252
20.0     1157
55.0     1047
70.0     1030
65.0     1024
22.0      886
28.0      794
Name: count, dtype: int64

### Verificación manual de valores

Una vez más revisemos los valores que no fueron procesados. En total quedan 201 edades únicas que convertir. En este caso se hará una tabla de conversión manual.

In [65]:
df.loc[ (df['Edad_str'].notna()) & (df['Edad_int'].isna()), ['Tipo_restos','Edad_str','Edad_int'] ].drop_duplicates()

            Tipo_restos  Edad_str  Edad_int
16347           Cadáver    6 dias       NaN
27520           Cadáver   30 dias       NaN
29285           Cadáver   4 meses       NaN
29497           Cadáver   3 meses       NaN
29613           Cadáver   14 dias       NaN
...                 ...       ...       ...
72088           Cadáver   50 dias       NaN
72128           Cadáver  39 meses       NaN
73300           Cadáver     18-25       NaN
73922  Miembros u óseos   9 meses       NaN
74042  Miembros u óseos  18 meses       NaN

[206 rows x 3 columns]

En este caso haremos una sustitución semiautomática, la cual hemos guardado en un archivo por el tamaño.

In [66]:
dic_edad = pd.read_csv('data_raw/cat_edad_sustitucion.csv')
display( dic_edad.head() )
dic_edad = {k:v for k,v in zip(dic_edad['edad_str'],dic_edad['edad_int'])}
dic_edad

  edad_str  edad_int
0   6 dias       0.0
1  30 dias       0.0
2  4 meses       0.0
3  3 meses       0.0
4  14 dias       0.0

{'6 dias': 0.0,
 '30 dias': 0.0,
 '4 meses': 0.0,
 '3 meses': 0.0,
 '14 dias': 0.0,
 '18 dias': 0.0,
 '3 semanas': 0.0,
 '2 meses': 0.0,
 '3m': 0.0,
 '3a': 3.0,
 '4a': 4.0,
 '19m': 1.0,
 '14m': 1.0,
 '10 dias': 0.0,
 '16m': 1.0,
 '18m': 1.0,
 '9m': 0.0,
 '2m': 0.0,
 '6m': 0.0,
 '4m': 0.0,
 '8 dias': 0.0,
 '8 meses': 0.0,
 '18 meses': 1.0,
 '25 dias': 0.0,
 '20 meses': 1.0,
 '6 meses': 0.0,
 '9 meses': 0.0,
 '1 mes': 0.0,
 '5 meses': 0.0,
 '20 dias': 0.0,
 '14 meses': 1.0,
 '11 dias': 0.0,
 '3meses': 0.0,
 '15 dias': 0.0,
 '11 meses': 0.0,
 '10 meses': 0.0,
 '12 dias': 0.0,
 '21 dias': 0.0,
 '10 semns': 0.0,
 '40 dias': 0.0,
 '7 meses': 0.0,
 '3 dias': 0.0,
 '72 horas': 0.0,
 '5 dias': 0.0,
 '1 y 8 meses': 0.0,
 '15 meses': 1.0,
 '48 dias': 0.0,
 '16 meses': 1.0,
 '22 meses': 1.0,
 '?': nan,
 '13 dias': 0.0,
 '1 meses': 0.0,
 '1 dias': 0.0,
 '26 dias': 0.0,
 '45 dias': 0.0,
 '[8]': 8.0,
 '4 dias': 0.0,
 '19 dias': 0.0,
 '17 dias': 0.0,
 '1 dia': 0.0,
 '7 dias': 0.0,
 '22 dias': 0.0,
 '16 dias': 0.0,
 '1 ano 4 meses': 1.0,
 '9 dias': 0.0,
 '2 dias': 0.0,
 '41 dias': 0.0,
 '1,5': 1.0,
 '1 ano 3 meses': 1.0,
 '7,5': 7.0,
 '1.3 meses': 0.0,
 '1.5 meses': 0.0,
 '2,5': 2.0,
 '-12 horas': 0.0,
 '6.5 meses': 0.0,
 '36 dias': 0.0,
 '25-30': 27.5,
 'f': nan,
 '1 1/2 anos': 0.0,
 '46 dias': 0.0,
 '30 meses': 2.0,
 '2.5 anos': 2.0,
 '1.5 anos': 1.0,
 '2.5 meses': 0.0,
 '3.5 anos': 3.0,
 '17 meses': 1.0,
 '53 dias': 0.0,
 '[1-10 dias]': 0.0,
 '12 meses': 1.0,
 '27 dias': 0.0,
 '19 meses': 1.0,
 '4.5 anos': 4.0,
 '42 dias': 0.0,
 '7.5 meses': 0.0,
 '13a': 13.0,
 '18a': 18.0,
 '1a': 1.0,
 '5m': 0.0,
 '25-40': 32.0,
 '6 semanas': 0.0,
 '20 o 24': 22.0,
 '28 dias': 0.0,
 '2 anos': 2.0,
 '2 1/2a': 2.0,
 '3 1/2': 3.0,
 '6a': 6.0,
 '12a': 12.0,
 '7a': 7.0,
 '2 1/2': 2.0,
 '24 dias': 0.0,
 '13 meses': 0.0,
 '72 hrs': 0.0,
 '-': nan,
 '23 meses': 0.0,
 '15 mese': 0.0,
 '3 anos y medio': 3.0,
 '18 m': 1.0,
 '3 m': 0.0,
 '1 1/2': 1.0,
 '8 1/2 meses': 0.0,
 '15a': 15.0,
 '1d': 0.0,
 '15d': 0.0,
 '5a': 5.0,
 '24d': 0.0,
 '1 1/2a': 1.0,
 '6 1/2m': 0.0,
 '17a': 17.0,
 '5d': 0.0,
 '6d': 0.0,
 '8m': 0.0,
 '16a': 16.0,
 '8d': 0.0,
 '3d': 0.0,
 '45d': 0.0,
 '14a': 14.0,
 '25/30': 27.0,
 '7 1/2': 7.0,
 '19d': 0.0,
 '17d': 0.0,
 '7d': 0.0,
 '10a': 10.0,
 '21d': 0.0,
 '2 1/2 m': 0.0,
 '16d': 0.0,
 '2a': 2.0,
 '3 anos': 3.0,
 '6 anos': 6.0,
 '9 anos': 9.0,
 '12 anos': 12.0,
 '17 anos': 17.0,
 '1 ano': 1.0,
 '13 anos': 13.0,
 '5 anos': 5.0,
 '4 anos': 4.0,
 '18 anos': 18.0,
 '65 meses': 5.0,
 '7 anos': 7.0,
 '8 anos': 8.0,
 '2/6': 4.0,
 '10 anos': 10.0,
 '11 anos': 11.0,
 '16 anos': 16.0,
 '15 anos': 15.0,
 '14 anos': 14.0,
 '1 anos': 1.0,
 '19 anos': 19.0,
 '1 1/2 meses': 0.0,
 '8 anos7': 8.0,
 '7 - 12 meses': 0.0,
 '1 - 3': 2.0,
 '2anos': 2.0,
 '30 - 90 dias': 0.0,
 '15-30 dias': 0.0,
 '12 horas': 0.0,
 '7 anoss': 7.0,
 '2 o 3 meses': 0.0,
 '26 meses': 2.0,
 '1 ano 7 meses': 1.0,
 'mas 72': 0.0,
 '5 meses 15 dias': 0.0,
 'm': nan,
 '3.5 meses': 0.0,
 '-72 h': 0.0,
 '73 dias': 0.0,
 '$45': 45.0,
 '2 1/2 a': 2.0,
 '9 a': 9.0,
 '1 1/2 a': 1.0,
 '2 m': 0.0,
 '8 semanas': 0.0,
 '41 n': 41.0,
 '81a': 81.0,
 '18 mese': 1.0,
 '2 mese': 0.0,
 'r.n': 0.0,
 '47 dias': 0.0,
 '8a': 8.0,
 '50 dias': 0.0,
 '39 meses': 3.0,
 '18-25': 21.0}

En este caso es muy importante el orden de las operaciones. Por ejemplo, hay '1' tanto en fetos cómo en cadáveres. En este caso podemos suponer por el contexto que representan cuestiones diferentes.

In [67]:
# Correción por catálogo
df['Edad_estandar'] = df['Edad_str'].replace(dic_edad)
# Edad especial a fetos y RN
df.loc[(df['Edad_estandar'].notna()) & (df['Tipo_restos'].isin(['Feto','Recién nacido'])) , 'Edad_estandar'] = 0
# Convertir a entero
df['Edad_estandar'] = pd.to_numeric(df['Edad_estandar'])
df['Edad_estandar'].unique()

array([  nan,   0. ,  63. ,  17. ,  69. ,  40. ,  68. ,  50. ,  42. ,
        66. ,  55. ,  60. ,  30. ,  48. ,  39. ,  35. ,  37. ,  56. ,
        62. ,  27. ,   4. ,  41. ,  25. ,  72. ,  16. ,  65. ,  26. ,
         8. ,  20. ,   3. ,  28. ,  58. ,  23. ,  22. ,  75. ,   1. ,
        24. ,  54. ,  19. ,  34. ,  80. ,  13. ,  36. ,  45. ,   2. ,
        61. ,  12. ,  70. ,  49. ,  95. ,  33. ,  32. ,  14. ,  57. ,
        85. ,  21. ,   5. ,  74. ,   7. ,  15. ,   6. ,  86. ,  11. ,
        47. ,  29. ,  52. ,  81. ,  84. ,  18. ,  38. ,  43. ,  53. ,
         1.5,   9. ,  44. ,  64. ,  73. ,  82. ,  83. ,  51. ,  77. ,
        10. ,  31. ,  46. ,  59. ,  79. ,  71. ,  67. ,  78. ,  90. ,
        76. ,  98. ,  93. ,   3.5,  87. ,  88. ,  89. ,  94. ,   4.5,
        92. ,   2.5, 103. ,   7.5,  91. ,  96. ,  97. , 102. , 100. ,
        27.5,  99. ,  28.2,   8.3,   2.2,  29.1,  25.1,  13.2,   5.3,
        27.1,   8.2,  18.2,  24.2,  23.2,   3.2, 108. , 116. , 107. ])

### Validación de rango

Veamos la distribución de edades:

In [68]:
df['Edad_estandar'].describe()

count    40172.000000
mean        35.236518
std         22.130567
min          0.000000
25%         20.000000
50%         34.000000
75%         50.000000
max        116.000000
Name: Edad_estandar, dtype: float64

Tenemos una persona de 116 años, esto podría ser un dato fuera de rango. 
En este caso vamos a poner un criterio para manejar problemas similares a futuro, si la persona tiene más de cien años remplazaremos su edad por `nan`.
Para lograr esto, seleccionaremos todas las celdas de personas de más de cien años que están en la columna 'Edad_años' con `.loc[]` y remplazaremos estos valores por `nan`.
Esto debe de cambiar la edad máxima de nuestros datos.

In [69]:
df.loc[ df['Edad_estandar']>=100,'Edad_estandar' ] = nan
df['Edad_estandar'].describe()

count    40156.000000
mean        35.209543
std         22.093515
min          0.000000
25%         20.000000
50%         34.000000
75%         50.000000
max         99.000000
Name: Edad_estandar, dtype: float64

### Grupos de edad con `.cut()`

Una operación común al trabajar con números es agrupar. Para dividir la edad en grupos usaremos la función `.cut()`. Esta función toma una serie de datos y el parámetro `bins`. Dado que nuestras edades van de 0 a 100, podemos dividir en 10 grupos.

In [70]:
df['Edad_grupo'] = pd.cut(df['Edad_estandar'], bins=10)
df['Edad_grupo'].dropna()

16347    (-0.099, 9.9]
26472    (-0.099, 9.9]
27520    (-0.099, 9.9]
29285    (-0.099, 9.9]
29497    (-0.099, 9.9]
             ...
74081     (19.8, 29.7]
74083      (9.9, 19.8]
74092     (19.8, 29.7]
74093     (59.4, 69.3]
74098     (19.8, 29.7]
Name: Edad_grupo, Length: 40156, dtype: category
Categories (10, interval[float64, right]): [(-0.099, 9.9] < (9.9, 19.8] < (19.8, 29.7] < (29.7, 39.6] ... (59.4, 69.3] < (69.3, 79.2] < (79.2, 89.1] < (89.1, 99.0]]

Esta función transforma la columna en categórica ordenada. Podemos ver los rangos que se incluyen en cada celda, nota que cada rango inicia con el valor con el que el anterior termina. El paréntesis `(` significa que no incluye el valor, mientras que el corchete `]` significa que sí se incluye el valor en el rango.

In [71]:
df['Edad_grupo'].value_counts(dropna=False).sort_index()

Edad_grupo
(-0.099, 9.9]     5955
(9.9, 19.8]       3691
(19.8, 29.7]      7633
(29.7, 39.6]      6250
(39.6, 49.5]      5433
(49.5, 59.4]      4138
(59.4, 69.3]      3490
(69.3, 79.2]      2597
(79.2, 89.1]       804
(89.1, 99.0]       165
NaN              56688
Name: count, dtype: int64

En el caso de las edades es recomendable usar el formato del INEGI, ya que nos permite comparar con datos existentes. Por ejemplo, veamos las [defunciones nacionales del periodo](https://www.inegi.org.mx/contenidos/productos/prod_serv/contenidos/espanol/bvinegi/productos/historicos/181/702825416966/702825416966.pdf).

<div>
<img src="./extras/inegi_defunciones_tabla.png" width="500"/>
</div>

En este caso definiremos los bins de manera explícita para que coincidan con los del INEGI. Nota cómo iniciamos la serie en -1 y la terminamos en 100 para manejar los valores extremos del rango. Además, se tuvo cuidado de incluir un bin especial para los menores de un año `[0, 1)`. Finalmente, modificamos la función para que incluya el valor de la izquierda del rango y excluya el valor límite de la derecha.

In [72]:
bins = [0, 1] + list(range(5, 85, 5)) + [100]
bins

[0, 1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 100]

In [73]:
df['Edad_grupo'] = pd.cut(df['Edad_estandar'], bins, right=False)
df['Edad_grupo'].dropna()

16347      [0, 1)
26472      [0, 1)
27520      [0, 1)
29285      [0, 1)
29497      [0, 1)
           ...
74081    [20, 25)
74083    [15, 20)
74092    [20, 25)
74093    [65, 70)
74098    [20, 25)
Name: Edad_grupo, Length: 40156, dtype: category
Categories (18, interval[int64, left]): [[0, 1) < [1, 5) < [5, 10) < [10, 15) ... [65, 70) < [70, 75) < [75, 80) < [80, 100)]

El resultado es una tabla que es posible comparar con los datos del INEGI.

In [74]:
df.pivot_table(index='Edad_grupo', columns='Sexo', aggfunc='count', values='Edad_transcrito')

/tmp/ipykernel_72286/2434046763.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table(index='Edad_grupo', columns='Sexo', aggfunc='count', values='Edad_transcrito')

Sexo        Femenino  Masculino  S-D
Edad_grupo
[0, 1)          1064       1459   76
[1, 5)           788       1166    0
[5, 10)          466        935    1
[10, 15)         326        911    0
[15, 20)         619       1834    1
[20, 25)         630       3180    0
[25, 30)         593       3230    0
[30, 35)         455       2578    0
[35, 40)         482       2734    1
[40, 45)         404       2349    0
[45, 50)         393       2287    0
[50, 55)         391       1966    1
[55, 60)         323       1456    1
[60, 65)         417       1450    0
[65, 70)         429       1193    1
[70, 75)         511       1058    0
[75, 80)         412        616    0
[80, 100)        444        525    0

## 6.g Limpieza de fechas

Las fechas se encuentran en formato `datetime64`, lo cual incluye, fecha y hora.
Este formato sigue el patrón: `yyyy-mm-dd hh:mm:ss`

En este conjunto las columnas de tiempo son:
* 'Fecha_transcrito'

In [75]:
df['Fecha_transcrito'].value_counts(dropna=False).index.tolist()[0:5]

['S-D', '1982-03-27', '1979-12-26', '1981-12-26', '1982-06-21']

En este caso es muy común ver las fechas con el formato '1982-03-27 00:00:00'. Esto es comúnmente el resultado de cómo la hoja de cálculo procesa las fechas. La mayor parte de las hojas de cálculo, como Excel, infieren automáticamente el tipo de dato. Esto puede generar problemas al leer el archivo. Hay dos formas de corregir esto, una es procesar la fecha como `str`, quitar el texto ' 00:00:00' y después transformar a fecha. Otra opción, y la más recomendada, es editar el tipo de columna en la hoja de cálculo y leer de nuevo el archivo. Si no has hecho esto, es necesario hacer la modificación en el archivo original y correr de nuevo todo el proceso de limpieza.


<div>
<img src="./extras/calc_change_type.png" width="400"/>
</div>

Convertiremos las fechas a datetime con `to_datetime()` y veremos en que casos fracasa la función.
Guardaremos el resultado en una columna con el sufijo `_date`.

**Nota:** Para entender esta función es muy importante ver en donde se agrega el modificador que indica una nueva columna

In [76]:
df['Fecha_estandar'] = pd.to_datetime(df['Fecha_transcrito'], errors='coerce')
display(df.loc[ (df['Fecha_transcrito'].notna()) & (df['Fecha_estandar'].isna()), ['Fecha_transcrito', 'Fecha_estandar'] ].drop_duplicates())

      Fecha_transcrito Fecha_estandar
2770               S-D            NaT
10937       1970-04-31            NaT
12766       1970-02-29            NaT
15392       1971-02-29            NaT
26128       1972-02-30            NaT
34844       1974-02-29            NaT
45884       1976-04-31            NaT
46016       1976-11-31            NaT
46718       1976-06-31            NaT
47889       1976-02-31            NaT
60730       1978-02-30            NaT
62431          1978-02            NaT
64287          1977-12            NaT
66623          1978-04            NaT
66624          1978-05            NaT
66979       1979-11-31            NaT
67068       1979-02-29            NaT
67069       1979-02-30            NaT
67070       1979-02-31            NaT
70128          1979-08            NaT
70130          1979-09            NaT
71845          1979-01            NaT
79483       1980-06-31            NaT
88090       1981-02-31            NaT
88281       31/04/1981            NaT

En este caso se puede ver que la conversión fallo solo en dos tipos de casos:
* Información incompleta '1979-01'
* Fecha no existente: '1979-02-31'

En este caso, ya que no hay forma de corregir estos errores, dejaremos las fechas cómo `nan`

### Generando columnas derivadas de fecha

Usando este tipo de dato ahora es posible seleccionar por año, mes, día, hora y minuto usando los comandos:

* columna.dt.year
* columna.dt.month
* columna.dt.day
* columna.dt.hour
* columna.dt.minute
* columna.dt.dayofweek (numerico)
* columna.dt.weekday (nombre en inglés)
* columna.dt.dayofyear (numerico)
* columna.dt.weekofyear (numerico)

Agregaremos columnas para marcar el día de la semana, del año y número de semanas.

In [77]:
df['Fecha_año'] = df['Fecha_estandar'].dt.year
df['Fecha_mes'] = df['Fecha_estandar'].dt.month
df['Fecha_diasemana'] = df['Fecha_estandar'].dt.weekday

Al agregar columnas es importante tomar en cuenta el tipo de dato. Por ejemplo, veamos las columnas de día de la semana. Estas asignan un número al día de la semana con Lunes=0 y Domingo=6.

In [78]:
df['Fecha_diasemana'].unique()

array([ 2.,  4.,  6.,  1.,  3.,  0.,  5., nan])

Editemos estas columnas para que tengan el día de la semana por su nombre y sean categóricos ordenados.

Lo primero es hacer un diccionario para sustituir los valores por el nombre del día de la semana.

In [79]:
dic_semana = {0:'Lunes', 1:'Martes', 2:'Miercoles', 3:'Jueves',
              4:'Viernes', 5:'Sábado', 6:'Domingo'}
df['Fecha_diasemana'] = df['Fecha_diasemana'].replace(dic_semana)
df['Fecha_diasemana'].unique()

array(['Miercoles', 'Viernes', 'Domingo', 'Martes', 'Jueves', 'Lunes',
       'Sábado', nan], dtype=object)

Ahora, generemos la categoría ordenada y transformemos las columnas a categórico.

In [80]:
orden_semana = ['Lunes', 'Martes', 'Miercoles', 'Jueves',
                'Viernes', 'Sábado', 'Domingo']
orden_semana = CategoricalDtype(categories=orden_semana, ordered=True)

df['Fecha_diasemana'] = df['Fecha_diasemana'].astype( orden_semana )
df['Fecha_mes'] = df['Fecha_mes'].astype("category")
df['Fecha_año'] = df['Fecha_año'].astype("category")
df.dtypes

ID                                    object
Nombre_completo_transcrito            object
Primer_apellido                       object
Segundo_apellido                      object
Nombres_propios                       object
Fecha_transcrito                      object
Procedencia_transcrito                object
Procedencia_estandar                category
Procedencia_extendido                 object
Procedencia_alcaldia                category
Diagnostico_transcrito                object
Diagnostico_estandar                category
Diagnostico_extendido                 object
Diagnostico_clasificacion           category
Sexo                                category
Edad_transcrito                       object
Tipo_restos                         category
Conocido_desconocido                category
Edad_str                              object
Edad_int                             float64
Edad_estandar                        float64
Edad_grupo                          category
Fecha_estandar                datetime64[ns]
Fecha_año                           category
Fecha_mes                           category
Fecha_diasemana                     category
dtype: object

In [81]:
df['Fecha_diasemana']

0        Miercoles
1          Viernes
2          Domingo
3          Domingo
4          Domingo
           ...
96839       Sábado
96840       Sábado
96841      Viernes
96842      Domingo
96843        Lunes
Name: Fecha_diasemana, Length: 96844, dtype: category
Categories (7, object): ['Lunes' < 'Martes' < 'Miercoles' < 'Jueves' < 'Viernes' < 'Sábado' < 'Domingo']

## 6.h Ordenar y guardar datos

Antes de guardar los datos veamos las columnas, esto nos dará una idea de que hemos hecho.

In [82]:
df.columns

Index(['ID', 'Nombre_completo_transcrito', 'Primer_apellido',
       'Segundo_apellido', 'Nombres_propios', 'Fecha_transcrito',
       'Procedencia_transcrito', 'Procedencia_estandar',
       'Procedencia_extendido', 'Procedencia_alcaldia',
       'Diagnostico_transcrito', 'Diagnostico_estandar',
       'Diagnostico_extendido', 'Diagnostico_clasificacion', 'Sexo',
       'Edad_transcrito', 'Tipo_restos', 'Conocido_desconocido', 'Edad_str',
       'Edad_int', 'Edad_estandar', 'Edad_grupo', 'Fecha_estandar',
       'Fecha_año', 'Fecha_mes', 'Fecha_diasemana'],
      dtype='object')

Al agregar columnas estas se ponen al final, por lo que sería bueno ordenarlas. Además, hay columnas de trabajo, cómo 'Edad_str' y 'Edad_int' que no son necesarias.

Este es también un buen momento de cambiar los nombres de las columnas en caso de que sea necesario, recuerda que puedes hacer esto con `df.columns=[new_names]` o `df.rename()`.

In [83]:
df = df[['ID', 'Nombre_completo_transcrito', 'Primer_apellido', 'Segundo_apellido', 'Nombres_propios', 
         'Fecha_transcrito', 'Fecha_estandar', 'Fecha_año', 'Fecha_mes', 'Fecha_diasemana',
         'Procedencia_transcrito', 'Procedencia_estandar', 'Procedencia_extendido', 'Procedencia_alcaldia',
         'Diagnostico_transcrito', 'Diagnostico_estandar', 'Diagnostico_extendido', 'Diagnostico_clasificacion',
         'Sexo', 'Edad_transcrito', 'Edad_estandar', 'Edad_grupo', 'Tipo_restos', 'Conocido_desconocido' ]]
df.tail()

,ID,Nombre_completo_transcrito,Primer_apellido,Segundo_apellido,Nombres_propios,Fecha_transcrito,Fecha_estandar,Fecha_año,Fecha_mes,Fecha_diasemana,...,Diagnostico_transcrito,Diagnostico_estandar,Diagnostico_extendido,Diagnostico_clasificacion,Sexo,Edad_transcrito,Edad_estandar,Edad_grupo,Tipo_restos,Conocido_desconocido
96839,BO_1982_07489,placenta,NaN,NaN,NaN,1982-06-05,1982-06-05,1982.0,6.0,Sábado,...,S-D,NaN,NaN,NaN,S-D,S-D,NaN,NaN,Miembros u óseos,Desconocido
96840,BO_1982_07490,5 dedos del pie derecho de desconocido,NaN,NaN,NaN,1982-06-05,1982-06-05,1982.0,6.0,Sábado,...,S-D,NaN,NaN,NaN,S-D,S-D,NaN,NaN,Miembros u óseos,Desconocido
96841,BO_1982_07491,dedo de desconocido,NaN,NaN,NaN,1982-11-19,1982-11-19,1982.0,11.0,Viernes,...,S-D,NaN,NaN,NaN,S-D,S-D,NaN,NaN,Miembros u óseos,Desconocido
96842,BO_1982_07492,4 dedos de desconocido,NaN,NaN,NaN,1982-11-28,1982-11-28,1982.0,11.0,Domingo,...,S-D,NaN,NaN,NaN,S-D,S-D,NaN,NaN,Miembros u óseos,Desconocido
96843,BO_1982_07493,osamenta de desconocido,NaN,NaN,NaN,1982-10-11,1982-10-11,1982.0,10.0,Lunes,...,S-D,NaN,NaN,NaN,S-D,S-D,NaN,NaN,Cadáver,Desconocido

Hagamos un nuevo profile para ver el comportamiento de los datos limpios

In [84]:
#!pip install ydata_profiling

from ydata_profiling import ProfileReport

file_profile = "profiles/HBO_profile_clean.html"
prof = ProfileReport(df) 
prof.to_file(output_file=file_profile)

Summarize dataset: 100%|█████████████| 35/35 [00:05<00:00,  6.28it/s, Completed]
Generate report structure: 100%|██████████████████| 1/1 [00:04<00:00,  4.19s/it]
Render HTML: 100%|████████████████████████████████| 1/1 [00:00<00:00,  3.00it/s]
Export report to file: 100%|█████████████████████| 1/1 [00:00<00:00, 127.53it/s]

Es posible guardar los datos limpios que hemos obtenido de varias formas, podemos guardarlos como CSV o Excel usando los comandos `.to_csv()` y `.to_excel()`. Estos formatos tienen la ventaja de que son fáciles de compartir. 

Nosotros guardaremos los datos limpios en la carpeta `data_clean` como un CSV, debido a que el tamaño de la base de datos es grande, puede ser complicado para manipularla en Excel. Sin embargo, es posible abrir archivos CSV usando Excel.

Es muy importante no rescribir los datos originales y tratar de tener una carpeta para cada parte del proceso de análisis, para evitar perder información y poder reproducir confiablemente nuestros análisis.

In [85]:
file_out = "data_clean/HBO_clean.csv"
df.to_csv(file_out)

Una desventaja de guardar los archivos usando CSV o Excel, es que podemos perder el formato y los tipos de datos. Esto es importante sobre todo para tipos de datos como `datetime` o `categorical`. Una opción es guardar nuestros datos en un formato que sea fácilmente interpretable para Python, aunque este no se pueda trabajar con Excel.

In [86]:
from joblib import dump

file_out_pickle = "data_clean/HBO_clean.pkl"
with open(file_out_pickle, 'wb') as f:
    dump(df, f)

## 6.i Resumen

En esta lección hemos aprendido varios conceptos:
  
* Antes de empezar a limpiar los datos es necesario plantear una estrategia que incluya para cada variable/columna
    * Tipo de variable
    * Limpieza necesaria
    * Validación de la limpieza
    * Ingeniería de variables derivadas
* Se pueden quitar datos con `.drop()`
* Es necesario revisar los datos faltantes y duplicados
* Limpieza de texto `df[col].apply(str)`
    * Remplazar textos o parte del texto `replace` y `RegExp`
    * Capitalización `.upper()`, `.lower()`, `.title()`, `.capitalize()`
    * Acentos `unidecode`
    * Puntuación y caracteres especiales `RegExp`
    * Espacios `' '.join(s.split())`:
* Limpieza de categóricos `.astype('category')`:
    * Fijar el catálogo válido
    * Ordenar el catálogo si es necesario
    * Hacer una tabla de equivalencias `replace` y `merge`
* Limpieza números `pd.to_numeric()`:
    * Puede ser necesario hacer limpieza manual
    * Generar grupos con `.cut()`
* Limpieza de fechas `pd.to_datetime()`:
    * Se pueden obtener, año, mes, día, día de la semana, etc
* Guardar
    * Es necesario validar la limpieza antes de guardar
    * En formato CSV para compartir `.to_csv()`
    * En formato pickle para analizar en Python `joblib.dump`

    
**¡Gracias!**